### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by pmosconi** [awslabs/aws-serverless-express#1]
Hi,
this is great work and the proxy API concept will really really make things a lot easier!
Since I'm one of the few developing node on a Windows machine (actually we are quite a few ...) I'd really love to see this library working seamlessly also on Windows.

It took me just an hour to set-up a medium complexity project (about 10 end-points, token authentication middleware, several folders and host of 3rd party libraries, a bunch of AWS additional services to give authorization too) and I just ran in 2 issues that can be easily resolved or worked around since they both are related to command scripting in package.json:

1. zip - `"Package Function": "zip -q -r lambda-function.zip lambda.js app.js node_modules ..."`. The best practice for command line zip in windows is to use 7zip which is open source and doesn't need installation, so this command would translate into `7z a lambda-function.zip -r lambda.js app.js node_modules\ ...`. Would it be possible to have a platform dependent variant of the script, something like "Package-Function-Win"?
2. open the cloudformation console from the command line - `open https://console.aws.amazon.com/cloudformation/home?region=$npm_package_config_region` in `create-stack`.  This is not really a Win issue, actually after erroring on zip I used Bash in Ubuntu on Windows (the new Win10 command line Ubuntu subsystem) to make it work, but it is related to not having a GUI interface altogether. I'm not a linux guy so it took me a while to figure out where the error `Couldn't get a file descriptor referring to the console` was coming from and what it really meant: I finally got back to my browser (in Windows) to discover that everything was completed and perfectly up and running! So my 2 cents here would be to just take the open command part out of the script an have us users open a link in the browser.

These are really minor things!
Thanks
paolo

**Comment by brettstack** [comment]
Hi paolo, thanks for the report.

I'll spin up a Windows VM and get it working with "-win" suffixed commands.

As for environments with no GUI - since I imagine this would be the vast minority - I'll just call out the error in the README.

**Comment by brettstack** [comment]
I have updated package.json with `win-` prefixed commands. Best solution might be to get rid of these `scripts` and instead add a Node.js script which plays better cross-platform.

**Comment by pmosconi** [comment]
Hi brettstack, great work! Thanks again
paolo

**Comment by pmosconi** [comment]
Hi brettstack, great work!
Thanks again
paolo
