### ISSUE TITLE
Docs and rationale for AWS SAM?

### ISSUE THREAD

**Issue by richburdon** [awslabs/aws-serverless-express#102]
The README getting started is nice and clear, then when I look at the example, there's a ton of stuff I have no idea about; suddenly there's no serverless.yml file and an entire research project to figure about AWS SAM -- which on the face of it seems to make the nice serverless abstraction (prevent AWS-locking) go away?

Is there a middleground? I.e., a demo somewhere in the middle that stays with the serverless.yml approach (or is this being deprecated).

E.g., I have the README demo working (great). But 

1). I'm trying to figure out how to have an endpoint work with multiple express paths.

2). Are views directories (for template libs) automatically included; can they be configured in a serverless.yml file -- or do we need to jump into the AWS SAM new world.

Thanks.

**Comment by brettstack** [comment]
This is not related to "The Serverless Framework", though I imagine you can use that framework with this package.

**Comment by richburdon** [comment]
OK thanks.
