### ISSUE TITLE
Images not served properly

### ISSUE THREAD

**Issue by richburdon** [awslabs/aws-serverless-express#104]
I'm using `app.use('/static', express.static(ENV.STATIC_DIR))` to serve PNG and ICO files. 

The files are served but not displayed, seems to have the correct Content-Type but are blank (black rectangle).

The "Response" tab in the Chrome Network view shows binary text (usually this is blank for correctly served images), so I'm guessing there's an encoding issue but I haven't experienced this before with Express.

**Comment by brettstack** [comment]
Hi @richburdon there are many issues documenting how to serve binary. It mainly boils down to 2 things:

1. Ensure your content-type is defined in the third parameter of the main function `awsServerlessExpress.createServer(app, null, ['image/png'])`
1. Ensure the content type is listed in the API Gateway configuration (or simply */* to handle all content types) https://github.com/awslabs/aws-serverless-express/blob/master/example/simple-proxy-api.yaml#L99

**Comment by richburdon** [comment]
Hi @brettstack, thanks for your response.

#1. Yes I'm doing that.

#2. I'm using `serverless.yml` so this doesn't make sense to me. I'm trying manually to configure the API gateway and the service's binary support is configured for "image/png"

**Comment by omurphy27** [comment]
I had a similar problem, where the content-length returned was longer than it should have been. @brettstack's solution worked for me, except I was using zip files (`application/zip`). 

In my case, the binary mime types passed into the `awsServerlessExpress.createServer` function had to exactly match the ones defined in the AWS API Gateway console under 'Binary Support'.

I was passing in multiple mime types to the createServer function, but only had application/zip defined in the API gateway Binary Support section and it wasn't working. When I only passed in application/zip and also only had that under binary support, then it worked.

**Comment by brettstack** [comment]
@richburdon try adding "image/*" to your binary types array in createServer.

**Comment by richburdon** [comment]
Hi @brettstack I've tried that and it doesn't make any difference.

~~~~
const binaryMimeTypes = [
  'image/*',
  'image/jpeg',
  'image/png',
  'image/svg+xml',
];

let server = awsServerlessExpress.createServer(app, null, binaryMimeTypes);
~~~~

I've also set the binary type specifically in the API gateway, and tried configuring the serverles `serverless-apigw-binary` plugin (which also correctly sets the API gateway binary support).

I'm now serving the assets from S3 instead.

Again setting the 'accept: image/png' header explicitly works, but I can't do this in an `img` tag, which adds more types to the `accept` header (seems that an exact match is required).

**Comment by brettstack** [comment]
I'll look into this. S3 is the best way to serve static assets.

**Comment by richburdon** [comment]
Thanks Brett, yes I agree re S3, just puzzling.

**Comment by mhanney** [comment]
I am having the same issue with png and jpegs having the wrong content length, and (I think) wrong encoding. I am using  aws-serverless-express 3.0.2, express 4.16.2, and serverless.

I have tried ..

```
const server = awsServerlessExpress.createServer(app, null, ['image/png']);
```

and have put `*/*` in the API Gateway Binary Support Binary media types

Response headers - API Gateway fronted Lambda/Express app

```
accept-ranges:bytes
cache-control:public, max-age=0
content-length:51977
content-type:image/png
date:Fri, 01 Dec 2017 04:28:34 GMT
etag:W/"6ddb-160104c73b0"
last-modified:Fri, 01 Dec 2017 04:18:54 GMT
status:200
via:1.1 bdf69c9338fccde2f01f587a28200671.cloudfront.net (CloudFront)
x-amz-cf-id:B7oHN1Yvv4-qp2tOBUHDgjJzQKFA0kBozLoCCmjYdrNHPt08CieIuQ==
x-amzn-remapped-connection:close
x-amzn-remapped-content-length:28123
x-amzn-remapped-date:Fri, 01 Dec 2017 04:28:34 GMT
x-amzn-requestid:1802487b-d650-11e7-aac1-df5f6064ba25
x-amzn-trace-id:sampled=0;root=1-5a20da72-14e2367a9bd25bcdf20a571c
x-cache:Miss from cloudfront
x-powered-by:Express
```


chrome preview tab
```
aVZCT1J3MEtHZ29BQUFBTlNVaEVVZ0FBQUh...
```


chrome response tab
```
iVBORw0KGgoAAAANSUhEUgAAAHwAAAfeCAMAAAAN...
```


Same png on S3 backed CloudFront (working fine, but can't use it easily because my assets are referenced with relative paths in js and css files bundled by webpack and served by Express.) 

Response headers

```
accept-ranges:bytes
age:23786
content-length:28123
content-type:image/png
date:Thu, 30 Nov 2017 22:00:17 GMT
etag:"9c74e172f87984c48ddf5c8108cabe67"
last-modified:Thu, 30 Nov 2017 21:51:36 GMT
server:AmazonS3
status:200
via:1.1 5ecfd97124a5b15f1245ab731d34efe7.cloudfront.net (CloudFront)
x-amz-cf-id:vk3sdR45v-T6L1nEziN3dcZmNGmE2K5JKL0L7CJCXsOHhaziIOckwA==
x-amz-meta-cb-modifiedtime:Thu, 30 Nov 2017 17:32:59 GMT
x-cache:Hit from cloudfront
```

chrome preview tab
```
iVBORw0KGgoAAAANSUhEUgAAAHwAAAfeCAMAAAAN
```


chrome response tap
```
?PNG


IHDR|Þ
³ªçPLTEýýýõõõùùúòòó ...
```


Notice how the the chrome `response` tab contents in the API Gateway/Lambda/Express example (not working)
is the same as the the chrome `preview` tab contents in the S3 backed example (working).


I swear this worked 24 hours ago, and without having to specify ['image/png'] in the createServer call, or anything in the API Gateway Binary media types.

**Comment by mhanney** [comment]
I just redeployed my Express app (using serverless) 10 minutes after making the post above and it is working!

Response headers - API Gateway fronted Lambda/Express app (Working!)

```
accept-ranges:bytes
cache-control:public, max-age=0
content-length:28123
content-type:image/png
date:Fri, 01 Dec 2017 05:22:28 GMT
etag:W/"6ddb-160108127e0"
last-modified:Fri, 01 Dec 2017 05:16:28 GMT
status:200
via:1.1 f1836a6a7245cc3f6e190d259a0d9273.cloudfront.net (CloudFront)
x-amz-cf-id:JSI02VfrmPhwTQencPMI-lMuO9OwlmW_1yLRoHmTLHBzJG_iXk4Cfw==
x-amzn-remapped-connection:close
x-amzn-remapped-content-length:28123
x-amzn-remapped-date:Fri, 01 Dec 2017 05:22:28 GMT
x-amzn-requestid:9fa8ae0e-d657-11e7-93d7-890477579a7f
x-amzn-trace-id:sampled=0;root=1-5a20e714-d432afd7e2f4f7315a7d9a61
x-cache:Miss from cloudfront
x-powered-by:Express

```

chrome preview tab
```
iVBORw0KGgoAAAANSUhEUgAAAHwAAAfeCAMAAAAN
```


chrome response tap
```
PNG


IHDR|Þ
³ªçPLTEýýýõõõùùúòòó ...
```

**Comment by enapupe** [comment]
@mhanney I'm not exactly sure how you fixed this thing. I'm facing exactly the same issue: if the request has `Accept: image/png' I get the correct binary response, otherwise just some garbage base64... But browsers don't specify image/png, just image/*.. What should I do here?

**Comment by brettstack** [comment]
You can configure API Gateway and aws-serverless-express to serve binary on image/*

**Comment by enapupe** [comment]
Nope. Still can't make it work. This is very confusing:

<img width="750" alt="screen shot 2018-07-26 at 09 25 21" src="https://user-images.githubusercontent.com/291082/43262266-e782ea84-90b5-11e8-8f50-8e7829cd8a1f.png">
and 
<img width="403" alt="screen shot 2018-07-26 at 09 25 32" src="https://user-images.githubusercontent.com/291082/43262267-e953ae8e-90b5-11e8-9cdf-23a417167e48.png">

and I have re-deployed my function, just in case.

Am I missing something obvious?!

**Comment by Bnaya** [comment]
I'm having the same issue,
I've followed all of the steps i could find.
The code dose works with serverless-offline
example link:
https://fo1kcsjku4.execute-api.eu-central-1.amazonaws.com/dev/static/media/foundit.5284f9f8.png
Real resource 
![foundit 5284f9f8](https://user-images.githubusercontent.com/1304862/54887338-9730d200-4e9a-11e9-98fb-783ca832a3f7.png)

![Screen Shot 2019-03-25 at 1 10 21](https://user-images.githubusercontent.com/1304862/54887358-d0694200-4e9a-11e9-98e8-be22f94fa9a4.png)

Ideas? :)

**Comment by throrin19** [comment]
Does not works in my part : 

![image](https://user-images.githubusercontent.com/1394778/98973169-b2d76900-2513-11eb-8074-ab0a552b8704.png)


```js
const binaryMimeTypes = [
        'application/pdf',
        'application/zip',
        'multipart/form-data',
        'image/png',
];

const server = awsServerlessExpress.createServer(app, null, binaryMimeTypes);
```

```js
const img = // buffer

res.writeHead(200, {
     'Content-Type'      : 'image/png',
     'Content-Length'    : Buffer.byteLength(img),
});
res.end(img, 'binary');
```

This is the response headers : 

```
content-type | image/png
-- | --
content-length | 12832
date | Thu, 12 Nov 2020 17:19:56 GMT
x-amzn-requestid | 748f1270-858c-490f-b8c3-6b027b851f38
referrer-policy | no-referrer
x-dns-prefetch-control | off
x-permitted-cross-domain-policies | none
x-xss-protection | 0
access-control-allow-origin | *
expect-ct | max-age=0
strict-transport-security | max-age=15552000; includeSubDomains
x-frame-options | SAMEORIGIN
x-amzn-remapped-content-length | 9623
content-security-policy | default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
x-amzn-remapped-connection | close
x-download-options | noopen
x-amz-apigw-id | V549XGDsjoEFZoA=
x-content-type-options | nosniff
x-amzn-trace-id | Root=1-5fad6ebb-7ae0055e3e7ade66785664b9;Sampled=0
x-amzn-remapped-date | Thu, 12 Nov 2020 17:19:56 GMT
x-cache | Miss from cloudfront
via | 1.1 f41c2361062c4fc74c645f4e4fddd2de.cloudfront.net (CloudFront)
x-amz-cf-pop | CDG3-C2
x-amz-cf-id | Ta3zu9RRoDRL5Cfyi0wtrzrgk_fv3DbVRZDEMUa2v24DQrApH5K3cw==
```

And the image is still in base64 and not show correctly in insomnia/postman with or without `Accept : image/png` header.

**Comment by jakecoppinger** [comment]
For anyone still having this issue, see https://github.com/vendia/serverless-express/issues/104#issuecomment-476011130 above - they fixed it!

For me, `awsServerlessExpress.createServer(app, null, ['image/*', 'image/png'])` did the trick. See the top voted answer on https://stackoverflow.com/questions/35804042/aws-api-gateway-and-lambda-to-return-image for setting up AWS.

**Comment by sjerratsch** [comment]
I was having this issue some time ago and faced it now again and wondered why the hell the settings with binary response in my code and "*/*" in the API Gateway in AWS did not work. 

Then I remembered that this little detail drove me crazy in the past when I couldn't fix it for days:

**you have to click on "Deploy API" (under "Resources" => "Actions") after you made changes in the AWS API Gateway Settings, when using the AWS Web Console! This might not apply when using aws cdk for deployment, but definitely when using the web console. It's so unintuitive because one assumes that the changes are saved after clicking on "Save changes"...**
