### ISSUE TITLE
Get data from firebase hang up, lead to timeout

### ISSUE THREAD

**Issue by ittus** [awslabs/aws-serverless-express#107]
Getting data from `firebase` hang up. It's ok to run on local with `serverless-offline`, but when deploy to aws lambda, function stucks at reading data line.

### Example
```javascript
let data = (await crmApp.database().ref('people').once('value')).val()
```

### Environment
Node Version: 6.10.3
```
"firebase-admin": "^5.5.0"
"express": "^4.16.2",
"aws-serverless-express": "^3.0.2",
"serverless-webpack": "3.1.2",
"serverless": "^1.24.1",
"babel-core": "^6.26.0",
"babel-loader": "7.1.1",
"babel-plugin-transform-runtime": "^6.22.0",
"babel-preset-es2015": "^6.24.1",
"babel-preset-stage-0": "^6.22.0",
"babel-preset-stage-3": "^6.24.1",
```

**Comment by brettstack** [comment]
Are you transpiling? async/await is not available until Node.js 8

**Comment by ittus** [comment]
Yes, I'm using babel with config

```
{
  "plugins": ["transform-runtime", "babel-plugin-transform-flow-strip-types"],
  "presets": ["es2015", "stage-3"]
}
```

**Comment by ittus** [comment]
I found the issue. The reason is firebase private key is mismatch with account.
Normally it will print some warning message on console.
