### ISSUE TITLE
questions about jade route

### ISSUE THREAD

**Issue by JadyLiu** [awslabs/aws-serverless-express#11]
I am new to serverless, and try to get my simple express site working on AWS lambda + api-gateway.

When testing you need to append /pets(whatever) in the browser address after the stage name of the api gateway, while in my jade code is something like:
ul.nav.navbar-nav
  li  
    a(href="/page1") Page1
  li
    a(href="/page") Page2
The jade route does not have the stage name, so it gives errors after deploying to api gateway. Just want to know if I understand correctly and how i can fix it to get it work publicly?

**Comment by brettstack** [comment]
Hi @JadyLiu, if you're using the middleware (it's used in the example), you can pass `req.apiGateway.event.eventContext.stage` to your Pug (Jade) template and change your links to be `a(href="/#{stage}/page1")`

```js
pug.renderFile('template.pug', {
  stage: req.apiGateway.event.eventContext.stage
})
```

Alternatively (and probably preferred for production apps), you can look into setting up a [Custom Domain Name](http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html).

**Comment by JadyLiu** [comment]
@brettstack I use the middleware and pass the variable to my jade template and it works locally.
But after deploying to AWS, lambda function has errors as 

TypeError: Cannot read property 'stage' of undefined

I render the page from my app.js:

app.get('/*/page1', (req, res) => {
    res.render('page1' ,{
    stage: req.apiGateway.event.eventContext.stage
  });
});

Is there anything I should change to get it work ?

**Comment by brettstack** [comment]
Apologies, it is `requestContext` (`req.apiGateway.event.requestContext.stage`)

**Comment by brettstack** [comment]
I will update the example to showcase this.

**Comment by brettstack** [comment]
Added in #52
