### ISSUE TITLE
How to serve static folder, get 403

### ISSUE THREAD

**Issue by Derek-X-Wang** [awslabs/aws-serverless-express#112]
The index.html shows normally but all static folder files 403.
```
'use strict'
const express = require('express')
const path = require('path')
const app = express()

app.use('/static', express.static('./static'))

app.get('/', (req, res) => {
    res.sendFile(`${__dirname}/index.html`)
})

module.exports = app
```

Anything I did wrong?
Thanks

**Comment by syntacticsolutions** [comment]
I'm having the same problem

**Comment by brettstack** [comment]
Use relative file path rather than __dirname

**Comment by syntacticsolutions** [comment]
Thank you. I forget to add this to my server.js config.

```app.use(express.static('dist'));```

That solved my problem. :)

**Comment by Derek-X-Wang** [comment]
Hi,

Thanks for the help! It has been a long time. I even forget which project I was working on...

Close for now.

Thanks
