### ISSUE TITLE
API Gateway trace-id doesn't match Lambda trace-id

### ISSUE THREAD

**Issue by slaypax** [awslabs/aws-serverless-express#115]
Using this this middleware in a certain way with Active Tracing enabled in Lambda, you can accidentally split your traces in two. This leaves your Lambda function trace *orphaned* as it's own trace, with the API Gateway trace and downstream segments together in theirs

This happens because both API Gateway and Lambda create a new trace-ID. API Gateway doesn't support active tracing but it does add a trace ID to incoming requests. When this ID gets to lambda, the request continues with a different tracing-ID[1]. In this case, the one set by Lambda.  When the API Gateway request (and corresponding trace-id) are sent to Lambda, the trace-id  from API Gateway becomes a child of the new top level segment Lambda creates for your function. In other words, under normal circumstances, you don't need to create a new top level segment for subsequent HTTP requests made from lambda, since that's already been done for you by Lambda. The resulting new trace will show the API Gateway data, Lambda data, and can be passed downstream to continue the trace. 

How does this make it possible to split your traces in two? 

aws-serverless-express can create a new segment for tracing when you make a request. When it mapping the API Gateway event to  the HTTP request, the headers object is set using the headers from the event passed into the function on invocation by API Gateway[2]. The problem is that in this event is the header X-Amzn-Trace-Id, which contains the trace-id sent from API Gateway. Since we create a new top level segment when the middle ware makes it's request, this means that requests made this way will have a new trace-id, and not be connected to the trace started by Lambda when it created a new top level segment. 

You can work around this and still get the benefits of the information available when creating the new express segment, but make sure you use the correct trace id. The Lambda trace id is as a Lambda Environment variable called process.env._X_AMZN_TRACE_ID. 

1.https://docs.aws.amazon.com/xray/latest/devguide/xray-services-apigateway.html
2.https://github.com/awslabs/aws-serverless-express/blob/649eaf25b6fd9b623aa1f70afb14e09fa3144abc/index.js#L34

**Comment by brettstack** [comment]
I believe this was fixed in API Gateway. Lmk if this is still an issue.
