### ISSUE TITLE
Refactoring to work with Terraform

### ISSUE THREAD

**Issue by syntacticsolutions** [awslabs/aws-serverless-express#119]
Hi, we're currently using Terraform where I work and I was wondering how difficult it would be to do the same thing in Terraform?

**Comment by brettstack** [comment]
This is build-tool/IAC-tool agnostic. The example uses SAM, but that's not
required. Open to PRs for a Terraform example. 👍

**Comment by syntacticsolutions** [comment]
I would love to if I knew how lol. Might have to enlist some help from my teammates.

**Comment by syntacticsolutions** [comment]
One of my coworkers is building something similar with Terraform. It is able to deploy and it's assumed to be running, but I built a ```/test``` endpoint that just sends a 200 response with the word test. All I get is an encrypted string. I also tried disabling the compression module still got the same thing. Do you have any idea how I could fix this?

**Comment by syntacticsolutions** [comment]
@brettstack,  Ok so I figured out the encrypted string issue. I was sending it was base64 because of the Lambda Function. Now I'm sending webpack js and css files to the front-end and this is what I get. My vendor.css file makes it through. My main.css files doesn't make it and gives me Error: Content Decoding Failed. Then my JS file just gives me a 502 error. Is it possible that the files are too big somehow? I also tried disabled and enabling gzip compression and enabling and disabling the binary mime types. Nothing worked.

**Comment by brettstack** [comment]
Disabling gzip in your Express, and binary mime types in your aws-serverless-express AND API Gateway (can do this via console; and then make sure you deploy your API again) should solve the issue. Does this work locally?

**Comment by syntacticsolutions** [comment]
Yes it works locally. I think the problem is that the file that I am serving up is too large for API Gateway/Lambda because my css files are being received but my js file is 12mb and I get a ```x-cache: Cloudfront Error``` header in the response. We've been going through the yaml configurations to find out how you are generating the s3 files and then serving them and we are unable to figure it out. Any help would be greatly appreciated. Thanks!

**Comment by brettstack** [comment]
Have you checked CloudWatch for errors? Best way is to:

1. Go to your Lambda function in the Lambda console
2. Click the monitoring tab and look for the Error chart
3. If you see any spikes, click-and-drag over the most recent spike
4. Click the logs button to be taken to the CloudWatch console for this function's logs and the time you selected

**Comment by syntacticsolutions** [comment]
This is the error that I'm getting.

23:18:43
body size is too long
2018/02/08/[$LATEST]4645e58b73114bb0ac75a106b37bb297
body size is too long

**Comment by syntacticsolutions** [comment]
But if I deploy this with the SAM configurations it works.

**Comment by brettstack** [comment]
Okay, so the response limit is 6MB which is why you're getting this error. The SAM configuration is likely working only because it has compression enabled. So if you can get compression (gzip) working, you should be good with your Terraform config.

**Comment by syntacticsolutions** [comment]
When and where should I be compressing the files?

**Comment by syntacticsolutions** [comment]
Ok I was able to change some of the Webpack configs to make the file smaller and everything seems to be working now but for some reason my gateway stops responding whenever I add a post route to my app.js. I even added a post route similar to the one in the example and it keeps making the entire site fail.

**Comment by brettstack** [comment]
Glad yo figured it out!
