### ISSUE TITLE
API Gateway doesn't support application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by syntacticsolutions** [awslabs/aws-serverless-express#122]
I know this isn't due to your framework, but I was wondering if you might know of a workaround. Our Okta SAML IDP is sending authentication responses to our serverless node in application/x-www-form-urlencoded data and we are using passport.js to parse the user data. Do you know of a way to convert the data so that it's still formData once it reaches my lambda function?

**Comment by brettstack** [comment]
Check out #92
