### ISSUE TITLE
Content-length not properly set

### ISSUE THREAD

**Issue by JonathanJonathanJonathan** [awslabs/aws-serverless-express#129]
If you try to load an image it will calculate the content-length by taking the length of the body buffer 
https://github.com/awslabs/aws-serverless-express/blob/500f04ead08ae057062b9bbeb3292eeb46ce54e1/index.js#L59

Later the body buffer is converted to a string, resulting in a different content-length https://github.com/awslabs/aws-serverless-express/blob/500f04ead08ae057062b9bbeb3292eeb46ce54e1/index.js#L84, so the length won't match. Which results in an ERR_CONTENT_LENGTH_MISMATCH error in the browser.

See screenshot:
![bug](https://user-images.githubusercontent.com/934563/37155294-d5c3ab80-22e2-11e8-92f8-28c70fb94fdd.jpg)

I fixed it by adding
`if(isBase64Encoded && typeof headers['content-length'] !== "undefined") {
                headers['content-length'] = body.length.toString()
            }`
after https://github.com/awslabs/aws-serverless-express/blob/500f04ead08ae057062b9bbeb3292eeb46ce54e1/index.js#L84

Not sure if this is a decent fix or if I'm missing something :)

**Comment by brettstack** [comment]
Closing. This will be merged soon #176
