### ISSUE TITLE
Unknown output type: JSON

### ISSUE THREAD

**Issue by gilesbutler** [awslabs/aws-serverless-express#13]
Hey Guys,

I'm getting this error when I run ```npm run setup``` - the stack gets created but any subsequent updates won't deploy.

```
> aws cloudformation create-stack --stack-name $npm_package_config_cloudFormationStackName --template-body file://./cloudformation.json --capabilities CAPABILITY_IAM --parameters ParameterKey=AwsServerlessExpressS3Bucket,ParameterValue=$npm_package_config_s3BucketName --region $npm_package_config_region


Unknown output type: JSON

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/gb/.nvm/versions/node/v4.3.2/bin/node" "/Users/gb/.nvm/versions/node/v4.3.2/bin/npm" "run" "create-stack"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! aws-serverless-express-example@1.1.0 create-stack: `aws cloudformation create-stack --stack-name $npm_package_config_cloudFormationStackName --template-body file://./cloudformation.json --capabilities CAPABILITY_IAM --parameters ParameterKey=AwsServerlessExpressS3Bucket,ParameterValue=$npm_package_config_s3BucketName --region $npm_package_config_region`
npm ERR! Exit status 255
```

**Comment by brettstack** [comment]
Hi @gilesbutler, what's your aws cli config look like?

What happens if you add `--output json` to the end of the command in `package.json`?

**Comment by gilesbutler** [comment]
Hey @brettstack 

I'm testing it with updating new functions so I had to add it to the end of ```update-function``` command. That fixed the problem though and now outputs JSON with no errors thanks.

Should that be added to every aws call then?

**Comment by brettstack** [comment]
It would be better to find the root cause of the problem, likely in your aws cli config

**Comment by gilesbutler** [comment]
Spot on! Thanks @brettstack - I ran ```aws configure``` and changed ```Default output format: JSON``` to ```text``` and now it's working perfectly!

Thanks for your help 👍

**Comment by optimus-kart** [comment]
@gilesbutler I had faced a similar issue changing "JSON" to "json" (lower case) after running aws configure solved the problem

**Comment by BOLT2612** [comment]
@optimus-kart your answer works better for me.  Both "text" and "json" solve the problem, but "json" gives nicely formatted, easily readable output.

**Comment by mohammed1982-erbil** [comment]
@optimus-kart , it work, with me, perfect
