### ISSUE TITLE
How to run this example using SAM local

### ISSUE THREAD

**Issue by sinistersig** [awslabs/aws-serverless-express#137]
Hi,
I am trying to run this example using SAM local using `sam local start-api --template cloudformation.yaml` however I receive an error when SAM local is trying to unmarshal the yaml file.

```
github.com/awslabs/aws-sam-local/router.yamlToJSON(0x183e060, 0xc420240ae0, 0xc4203a8570, 0x9)
```

Any assistance would be appreciated. Thanks.

**Comment by brettstack** [comment]
You'll need to wrap all of the `200` response keys (e.g. https://github.com/awslabs/aws-serverless-express/blob/master/example/simple-proxy-api.yaml#L14) in quotes `'200'`. We're working on fixing SAM Local so this doesn't break. There's also an issue with SAM Local and `ANY`. For now you'll need to **also** specify all methods you need.

**Comment by brettstack** [comment]
@sinistersig have you tried this out with the new version? I think this has been fixed.
