### ISSUE TITLE
Access for browser javascript

### ISSUE THREAD

**Issue by navneetccna** [awslabs/aws-serverless-express#138]
Can we access this direct from javascript aws-sdk using lambda.invoke(pullParams, function(err, data) { }); ? (instead using urls we can call lambda function directly)

So we do not need to use url we can directly use it from aws sdk.

**Comment by brettstack** [comment]
Can you clarify? You can already invoke the Lambda function directly without using API Gateway

**Comment by navneetccna** [comment]
Yes, but how can we pass url and query paramerters to the lambda function?

**Comment by brettstack** [comment]
So long as you send in an event object similar to API Gateway this will work.

**Comment by navneetccna** [comment]
Ok, can you please provide sample for this?

**Comment by brettstack** [comment]
https://github.com/awslabs/aws-serverless-express/blob/master/example/api-gateway-event.json

**Comment by navneetccna** [comment]
Thank you very much.

**Comment by brettstack** [comment]
Let me know how it goes!

**Comment by navneetccna** [comment]
when I am passing and event object to lambda.invoke it says UnexpectedParameter: Unexpected key 'event' found in params.


my parameter object is 

var pullParams = {
        FunctionName : 'AwsServerlessExpressStack-AwsServerlessExpressFunc-170AHG39ULUAG',
        InvocationType : 'RequestResponse',
        LogType : 'None',
        event: {
            "httpMethod": "GET",
            "//body": "{\"name\": \"Sam\"}",
            "path": "/users",
            "resource": "/{proxy+}",
            "queryStringParameters": {},
            "pathParameters": {
                "proxy": "users"
            },
            "headers": {
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
                "Accept-Encoding": "gzip, deflate, sdch, br",
                "Accept-Language": "en-US,en;q=0.8",
                "CloudFront-Forwarded-Proto": "https",
                "CloudFront-Is-Desktop-Viewer": "true",
                "CloudFront-Is-Mobile-Viewer": "false",
                "CloudFront-Is-SmartTV-Viewer": "false",
                "CloudFront-Is-Tablet-Viewer": "false",
                "CloudFront-Viewer-Country": "US",
                "Content-Type": "application/json",
                "Host": "xxxxxxxxxx.execute-api.us-east-1.amazonaws.com",
                "Upgrade-Insecure-Requests": "1",
                "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36",
                "Via": "1.1 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.cloudfront.net (CloudFront)",
                "X-Amz-Cf-Id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxx_xxxx==",
                "X-Forwarded-For": "11.111.111.111, 11.111.111.111",
                "X-Forwarded-Port": "111",
                "X-Forwarded-Proto": "http"
            },
            "requestContext": {
                "accountId": "111111111111",
                "resourceId": "xxxxxx",
                "stage": "prod",
                "requestId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                "identity": {
                    "cognitoIdentityPoolId": "us-east-1:6a8f59f2-9837-4953-a7aa-f3f2f2b71971",
                    "accountId": "",
                    "cognitoIdentityId": "",
                    "caller": "",
                    "apiKey": "",
                    "sourceIp": "11.111.111.111",
                    "cognitoAuthenticationType": "",
                    "cognitoAuthenticationProvider": "",
                    "userArn": "",
                    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36",
                    "user": ""
                },
                "resourcePath": "/{proxy+}",
                "httpMethod": "GET",
                "apiId": "xxxxxxxxxx"
            }
        }

      
    };

**Comment by brettstack** [comment]
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property it should be `Payload`

**Comment by navneetccna** [comment]
Ok, got it one more query do we need to pass accountId, cognitoIdentityId and apiKey as well ?

right now i am getting this response

{"statusCode":200,"body":"W3siaWQiOjEsIm5hbWUiOiJKb2UifSx7ImlkIjoyLCJuYW1lIjoiSmFuZSJ9XQ==","headers":{"x-powered-by":"Express","access-control-allow-origin":"*","content-type":"application/json; charset=utf-8","content-length":"46","etag":"W/\"2e-Lu6qxFOQSPFulDAGUFiiK6QgREo\"","vary":"Accept-Encoding","date":"Thu, 12 Apr 2018 05:05:04 GMT","connection":"close"},"isBase64Encoded":true}

**Comment by brettstack** [comment]
Depends on what your app expects. If it expects those things, then yes. Also, that body is base64 encoded. You won't be able to use that with direct to Lambda as you need API Gateway to decode that back into binary format. This may just be because it's a gzip you're returning?

**Comment by navneetccna** [comment]
Ok, got it. Its working now I got JSON es decoded. Thank you very much for clearing those things.
