### ISSUE TITLE
Can't Access Test Event Data

### ISSUE THREAD

**Issue by JimTheMan** [awslabs/aws-serverless-express#142]
Hi, I'm using the aws-serverless-express/middleware for an AWS lambda function. I want to be able to access the "Test Event" data object from the AWS console. I've tried "req.body", "req.apiGateway.events", "req.query"...

How can I access this test event object? I don't understand why this library would hide the arguments passed into the lambda function. It seems to me like a pretty obvious thing users would want to do so it seems very weird to me that the author could forget this important thing.

**Comment by brettstack** [comment]
If configured correctly you should be able to access via 'req.apiGateway.events`. See https://github.com/awslabs/aws-serverless-express/blob/master/example/app.js#L14 for configuring and line 18 for usage.

**Comment by JimTheMan** [comment]
Good call. Thank you!
