### ISSUE TITLE
Promises/Await Issue with 3rd Party Library (Shopify)

### ISSUE THREAD

**Issue by josephchan91** [awslabs/aws-serverless-express#143]
I'm using lambda to implement a small utility app that interacts with Shopify using [this](https://github.com/MONEI/Shopify-api-node) package. However, calling a promise-returning method of the library seems to cut short the execution of the function. It worked fine before I migrated it from Webtask and when testing locally. The code within my express function looks like this:

`// function runs until here`
`const order = await shopify.order.get(orderId);`
`// but doesn't make it to this point`

These are the error logs I'm getting:

CloudWatch log:
`{"message": "Internal server error"}`

API Gateway log:
`Execution failed due to configuration error: Malformed Lambda proxy response`

Does anyone know what could possibly be going on?

**Comment by villasv** [comment]
Maybe related to https://github.com/awslabs/aws-serverless-express/issues/134?

**Comment by brettstack** [comment]
You commented less than a minute before I responded! Thanks for the additional details. Can you add a catch to that promise? Looks like that's where it's failing since it doesn't hit that console.log

**Comment by josephchan91** [comment]
@brettstack I tried wrapping the promise statement with a try/catch:
```
try {
  console.log("going to get order");
  return shopify.order.get(orderId);
} catch(e) {
  console.log("got an error: " + e);
}
```

But I'm not getting any error log. So strange...
```
START RequestId: 5c46e40c-4eef-11e8-bb9a-b7da1c529c77 Version: $LATEST
2018-05-03T16:31:01.631Z	5c46e40c-4eef-11e8-bb9a-b7da1c529c77	going to get order
END RequestId: 5c46e40c-4eef-11e8-bb9a-b7da1c529c77
REPORT RequestId: 5c46e40c-4eef-11e8-bb9a-b7da1c529c77	Duration: 3003.26 ms	Billed Duration: 3000 ms Memory Size: 128 MB	Max Memory Used: 55 MB	
2018-05-03T16:31:02.733Z 5c46e40c-4eef-11e8-bb9a-b7da1c529c77 Task timed out after 3.00 seconds
```

**Comment by hungchai** [comment]
Did you try to give more memory to lambda (more than 128)?

**Comment by josephchan91** [comment]
Silly mistake. Increased my timeout from 3 seconds to 6 seconds and it worked. It slipped my mind that the shopify library I'm using has rate limiting and my lambda function was calling the shopify API 2-3 times. Closing this now :)

**Comment by brettstack** [comment]
@josephchan91 you need to do async/await if you're doing try/catch. Otherwise you need to handle errors using the Promise .catch

**Comment by josephchan91** [comment]
@brettstack just missed your comment again! It was a lambda configuration mistake on my end, sorry!
