### ISSUE TITLE
Are lambda invocation errors even possible?

### ISSUE THREAD

**Issue by villasv** [awslabs/aws-serverless-express#144]
I was using safe lambda deployments following the examples from the Serverless Application Model, but I've noticed that after introducing aws-serverless-express I don't see any invocation errors in my Lambda monitoring and no matter how many unhandled exceptions happen in my express app, those won't trigger the alarm.

Should I use API Gateway as my source of error metrics, instead? Or perhaps there's a way to make 4XX and 5XX requests count as lambda invocation errors again?

**Comment by brettstack** [comment]
That's right, you should be looking at API Gateway errors. Are there any issues with this? Anything we can do to improve?

**Comment by villasv** [comment]
Not really, I just asked to be sure that the lack of Invocation Errors was expected.

I think this is fine. It's just that the SAM docs recommend the CloudWatch Alarms to monitor the Lambda function directly so anyone using this package might take a while to notice that their alarms are effectively monitoring nothing.

If the future reader of the issue also comes from SAM and is interested in the "Safe Lambda Deployment" setup and is using the example in this repository as base, also be sure to update the Swagger definition to invoke the auto published alias instead of the current unqualified lambda call.
