### ISSUE TITLE
Serverless issue

### ISSUE THREAD

**Issue by kenzotan95** [awslabs/aws-serverless-express#150]
Hi i'm an AWS newbie over here. So far I've been through many sites and forums to search for the errors that i have been getting but am unable to do so. I'm doing this on AWS Cli.

After running sls deploy, i keep getting this on AWS endpoint
{"message": "Internal server error"}

After checking cloudwatch logs, this error popped out;
Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)

I have attached my zip file here for perusal;
[annotation.zip](https://github.com/awslabs/aws-serverless-express/files/2087709/annotation.zip)

Would appreciate any help that is provided, thanks!

**Comment by villasv** [comment]
Well, there's no `index.js` file in your package, only `lambda.js`. You might start fixing that. Either change the name of the handler module to `lambda` in your AWS Lambda configuration or rename your handler file.

This error may pop up if you have any missing dependency as well, IIRC.

**Comment by kenzotan95** [comment]
Thanks @villasv, i edited it and it works like a charm!
