### ISSUE TITLE
Why delete API Gateway Proxy Integration body?

### ISSUE THREAD

**Issue by yousef-s** [awslabs/aws-serverless-express#151]
https://github.com/awslabs/aws-serverless-express/blob/42a5501f2ef393461e6d53c4ab28ab343d83044b/index.js#L37

Spent a few hours trying to figure out what was preventing API Gateway Proxy Integrated Lambdas from receiving the API gateway request body, then found this.

As it seems proactive, is there any reason this is in place that we should be aware of?

**Comment by brettstack** [comment]
That's a clone of the event object without the body used for the middleware. When configured correctly, your body gets sent in the request
