### ISSUE TITLE
Best Way To Kill A Lambda Function?

### ISSUE THREAD

**Issue by JimTheMan** [awslabs/aws-serverless-express#158]
Hi,

I am wondering, if do this:

```
res.context.callbackWaitsForEmptyEventLoop = false
res.send({"hello": "wurld"})
```

does setting this callbackWaits param mean the lambda should end after send it called? I was looking for something like "succeed" or "callback" but couldn't find it. Is there a proper way to force-kill the lambda function after it sends a response?

**Comment by brettstack** [comment]
Could you clarify? With this library the response is sent immediately when your app responds to a request. It uses `context.succeed`. `callbackWaitsForEmptyEventLoop` is only when you use `callback`

**Comment by JimTheMan** [comment]
Here's what I mean, when I run this code:

![weebly1](https://user-images.githubusercontent.com/5354163/42166617-8f179d02-7dd9-11e8-83fc-4d5306689327.png)

then I get this output:

![weebly2](https://user-images.githubusercontent.com/5354163/42166798-243702c4-7dda-11e8-9a67-f3785eabd3ba.png)

After I call res.send it still prints the logs. What I want is when I call res.send (or something else that I could run immediately afterwards) that will short-circuit the lambda and send the response but not print the logs. It's similar to how the "return" statement allows you to break out of a function and immediately kill it. I would think I would always want this to happen since, after all, calling res.send again after the first time just results in a error message anyway.

**Comment by brettstack** [comment]
Hmm you'll need to be more explicit in what you're trying to accomplish. If you were to return on that res.send the logs obviously wouldn't be reached. But I assume there's something I'm missing that you're trying to do.

**Comment by JimTheMan** [comment]
oh, duhh...  💃
