### ISSUE TITLE
process.on('uncaughtException') no longer catches all exception in express

### ISSUE THREAD

**Issue by than-speedline** [awslabs/aws-serverless-express#16]
Hi, after using aws-serverless-express, i noticed that node process.on('uncaughtException') of our previous express application doesn't catch all exception from async callbacks anymore. Is there another way to catch all exception that cause the server to crash?

This happens when we use the "request" model and an uncaught exception happens in the callback of an request.

**Comment by brettstack** [comment]
Hi @than-speedline, could you provide a minimum reproducible example?

**Comment by brettstack** [comment]
`unhandledException` is not a native event. Try using `uncaughtException` https://nodejs.org/api/process.html#process_event_uncaughtexception

**Comment by than-speedline** [comment]
Sorry, i meant uncaughtException. I'll try to create a simple test case, please give me a sec.

**Comment by than-speedline** [comment]
Hi, i manage to get an example working. Here is the link to the gist.
https://gist.github.com/than-speedline/f26b0247fbb35dcf465195b06cc97bdb
The exception would be caught locally by runnin app.js, but with the lambda.js and running in a lambda function, the process would instead exit.

**Comment by than-speedline** [comment]
Just an update, I realized that Lambda doesn't support uncaughtException properly. So i guess this is not the problem with this library. This issue should probably be closed.
P.S. Someone has already asked uncaughtException in the form, here is the [link](https://forums.aws.amazon.com/thread.jspa?threadID=229830)

**Comment by jackrk** [comment]
Thanks for the update!

**Comment by Swivelgames** [comment]
@Tony-Donghua-Han Seems you unfortunately deleted the `gist` with your fix. That's unfortunate, given that Googlers aren't able to see your solution. 😅
