### ISSUE TITLE
Serve videos

### ISSUE THREAD

**Issue by romainquellec** [awslabs/aws-serverless-express#160]
Hello.

I'm trying to serve videos. Is there any restriction I dont know about with aws-serverless-express for that ?
Any svg, jpg works fine but my 5mo .mp4 seems to not work on lambda (working offline though).

**Comment by brettstack** [comment]
No, streaming won't work.

**Comment by romainquellec** [comment]
any reason for that ?

**Comment by romainquellec** [comment]
Thanks ! I'm closing this.
