### ISSUE TITLE
How To Use Nested Resources?

### ISSUE THREAD

**Issue by JimTheMan** [awslabs/aws-serverless-express#162]
By default my SAM temaplate from CodeStar creates _/Stage_ and _/Prod_ resources in api gateway. I want to add another resource on the end of the url so that it looks something like this:

![api_gateway](https://user-images.githubusercontent.com/5354163/42394327-c08a6cd8-8127-11e8-8c2f-2a2f155c44ab.png)

Then when I deploy this I have a working url that looks something like this:

`https:/XXXXXXX.us-east-2.amazonaws.com/Stage/`

which works fine.

But, when I try to call the url of the nested resource:

`https://XXXXXXX.us-east-2.amazonaws.com/Stage/send-score`

I always get this response: 

![error_and_stack_detail2](https://user-images.githubusercontent.com/5354163/42394642-d81fea52-8128-11e8-8225-2a52a2f453a9.png)

Is it aws-serverless-express that's causing my issues here, or is there something else I'm doing wrong?

thanks!

**Comment by brettstack** [comment]
It looks like your API Gateway configuration is correct because you are getting `Cannot GET /send-score` which is an Express error. So the problem is likely with your Express route. What does the Lambda `event.path` look like and does that match your route in Express?

**Comment by brettstack** [comment]
Is this still an issue?

**Comment by JimTheMan** [comment]
Hi Brett, I'm pretty the problem was with my code as I'm not having the issue anymore.

But I did was to ask you- I tried checking event.path (where event is the parameter in index.handler), but it seems to always be undefined.
