### ISSUE TITLE
APIGateway returns lambda response object instead of body of the response

### ISSUE THREAD

**Issue by bertyhell** [awslabs/aws-serverless-express#164]
My code:
```typescript
export function handler(event: APIGatewayEvent, context: Context) {
  try {
    const app: Application = getExpressApp();
    const server = awsServerlessExpress.createServer(app);
    return awsServerlessExpress.proxy(server, event, context);
  } catch (err) {
    context.fail('Failed to start server on lambda');
  }
}
```

The response if a make a request through api gateway:
![body](https://user-images.githubusercontent.com/1710840/42727107-93dbea16-87a0-11e8-9044-40e432cd3064.png)

But i was expecting to just get the json body:
```json
{
  "message": "hello from backend"
}
```

Am i doing something wrong or is this expected behavior?

**Comment by brettstack** [comment]
You should just be getting the body... I've never seen this happen before. This is actually going through API Gateway and not a local environment during Dev/test?

A quick aside comment: you should see performance improvements if you hoist app and server outside the handler scope.

**Comment by emrahayanoglu** [comment]
+1

**Comment by emrahayanoglu** [comment]
I found my problem on the response which is the wrong configuration of the API Gateway. It should be configured as Lambda Proxy Integration, otherwise all headers will be visible on the response.

I propose to close this ticket as it is a configuration issue on the API Gateway.

**Comment by bertyhell** [comment]
@emrahayanoglu  You're right. Thank you for the reply.

For anyone else hitting this issue, here are the steps to resolve it:

![image](https://user-images.githubusercontent.com/1710840/42941579-825114cc-8b5d-11e8-980a-381eb68a9168.png)

![image](https://user-images.githubusercontent.com/1710840/42941584-85f208fc-8b5d-11e8-9034-67c6b0c4a138.png)

![image](https://user-images.githubusercontent.com/1710840/42941595-890ca074-8b5d-11e8-89a3-a48ea639b649.png)

**Comment by brettstack** [comment]
Glad you figured it out. Thanks for the screenshots. Check out our example which I recommend using as a baseline and modifying from there. It uses SAM a d is a one-command deploy
