### ISSUE TITLE
does API gateway  endpoint supports  request Chunked transfer encoding  ?

### ISSUE THREAD

**Issue by bsdoma** [awslabs/aws-serverless-express#167]
Hi,

I have requirement to process stream of binary data  pass to Api gateway endpoint based on some corelationId as identity chunk by chunk  .
 
Please clarify the below issues :+1: 
1.Does api gateway  rest endpoint supports chunked transfer and keep the connection open until all chunks  processed / apio gateway endpoint connection closed  and return the response with all chunks of data .
2.How many number of aws lambda instances gets created when we invoke AWS api gateway endpoint multiple times ?

Regards,
Brahmaiah Doma

**Comment by brettstack** [comment]
1. No, API Gateway does not support chunked transfer.
1. Lambda will create a new instance only when it receives a request and all current instances are running.

**Comment by bsdoma** [comment]
that means for each request lambda service class instance gets created ?  is it ptototype /Singleton/Request scope  design pattern?

**Comment by brettstack** [comment]
Given an application with no other traffic:If I make a request, and then after receiving a response I make another request, this will be a single Lambda instance.

If you and I make a request at the exact same time, 2 Lambda instances will be created
