### ISSUE TITLE
Return blank webp image from S3 url with no any error

### ISSUE THREAD

**Issue by PatelPinal1415160** [awslabs/aws-serverless-express#168]
I've uploaded webp image into my S3 bucket but some of then return blank image when I try to open it in a browser. Content-Type: image/webp is also correct. It displays from the mobile side but not in any browser.

S3 return blank image like this: https://videoflyer.s3.us-east-2.amazonaws.com/videoflyer/webp_original/5b14e4b57da79_json_image_1528095925.webp

Does anybody have the solution?

**Comment by brettstack** [comment]
Sounds like an S3 question unrelated to this project.
