### ISSUE TITLE
Deployment fails with Cloudformation error

### ISSUE THREAD

**Issue by stilkov** [awslabs/aws-serverless-express#169]
When I try to deploy the basic-starter example application using the instructions from the README, the Cloudformation step fails with the following error:

```Errors found during import: Unable to put integration on 'ANY' for resource at path '/': Invalid ARN specified in the request Unable to put integration on 'ANY' for resource at path '/{proxy+}': Invalid ARN specified in the request```

**Comment by stilkov** [comment]
User error – sorry for the noise.

**Comment by obbaeiei** [comment]
@stilkov  Hi how you fix it? thanks

**Comment by rayjun** [comment]
@stikov I have same problem, how to fix it ?

**Comment by stilkov** [comment]
I had a typo in one of my region names.

**Comment by rayjun** [comment]
thanks!  You inspire me ,my region is cn-north-1 in china, so I must change aws to aws-cn! @stilkov
