### ISSUE TITLE
[Question] Streamed responses (callback)

### ISSUE THREAD

**Issue by enapupe** [awslabs/aws-serverless-express#170]
Hello guys! I'm asking you because you are the closest folks I can find that relate to aws lambda.
I want to know if lambda will have support for streamed responses on node.
That's the most important thing for me regarding serverless, my website now loads a bit slower/differently due the fact it only starts parsing html after receiving a full response.
THanks!

**Comment by brettstack** [comment]
I can't comment on feature availability in Lambda or API Gateway.
