### ISSUE TITLE
export getSocketPath

### ISSUE THREAD

**Issue by ispyinternet** [awslabs/aws-serverless-express#171]
My express app does some local requests and so without knowing the socket im unable to configure the request. Can you please export getSocketPath ?

**Comment by brettstack** [comment]
Exposing this as part of the middleware is probably the best approach. Do you want to make this PR? Otherwise I'll get to it when I can.

**Comment by ispyinternet** [comment]
I actually found I could read the socket from the request object...

    req.socket.server.address();

Not sure how stable / future proof but I’m thinking it’s good enough??

**Comment by brettstack** [comment]
Must be a Node.js or Express feature. Likely pretty future proof. Glad you figured it out. Closing.
