### ISSUE TITLE
Trowing error in async/await route times out when using async handler

### ISSUE THREAD

**Issue by andidev** [awslabs/aws-serverless-express#181]
So I'm not sure I am doing everything correctly here. But how come throwing an Error in this case causes the lambda to timeout?

How can I prevent the lambda from timing out?

```javascript
import express from 'express';
import awsServerlessExpress from 'aws-serverless-express';

const app = express();
app.get('/throwerror', async (req, res) => {
    throw new Error('This is an error');
});

const server = awsServerlessExpress.createServer(app);
export const handler = async (event: any, context: any) => awsServerlessExpress.proxy(server, event, context, 'PROMISE').promise;
```

**Comment by brettstack** [comment]
Thanks for the comment. This sounds like a bug. I'll fix and release as soon as I can

**Comment by brettstack** [comment]
This isn't a bug in this lib. It's an unhandled promise rejection at your application layer and must be handled there. If you do the same thing with a standard Express app and try to run it locally (without aws-serverless-express) you'll see it too times out.

**Comment by brettstack** [comment]
To more directly answer your question "How can I prevent the lambda from timing out?" - if you remove `async` from your route handler function it will return an HTML response with the error stack trace.

**Comment by andidev** [comment]
Removing async is not an option since I have asyncronious calls to the database. 
Using https://github.com/Abazhenov/express-async-handler workes though.

The reson why I created this bug was because I thought it was a bit extreme for the lambda to time out on a async error. But I guess it is not up to aws-serverless-express to take care of that.

**Comment by brettstack** [comment]
Express doesn't natively support  async/await, though they're aiming for it in Express 5. Today, you'll need to do something like:

```js
router.get('/user/:id', async (req, res, next) => {
  try {
    const user = await getUserFromDb({ id: req.params.id })
    res.json(user);
  } catch (e) {
    //this will eventually be handled by your error handling middleware
    next(e) 
  }
})
```

I took this example from here https://medium.com/@Abazhenov/using-async-await-in-express-with-node-8-b8af872c0016.

**Comment by brettstack** [comment]
I didn't see your comment before replying. Glad you found a solution. You're correct that this library doesn't (and can't/shouldn't) stop your Lambda from timing out.
