### ISSUE TITLE
Can't get the API Gateway event object

### ISSUE THREAD

**Issue by wooooooak** [awslabs/aws-serverless-express#182]
I use aws-serverless-express/middleware but can't get the API Gateway event object.
Here is my code.

```
...
import awsServerlessExpress from 'aws-serverless-express';
import awsServerlessExpressMiddleware from 'aws-serverless-express/middleware';
...

const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
api.use(awsServerlessExpressMiddleware.eventContext());

app.use('/', api);
const server = awsServerlessExpress.createServer(app);

exports.handler = (event, context) => awsServerlessExpress.proxy(server, event, context);
```

When i use access req.apiGateway.event, error has occurred like below.
`TypeError: Cannot read property 'event' of undefined`

Am i missing something? or is this bug?

**Comment by brettstack** [comment]
```js
api.use(awsServerlessExpressMiddleware.eventContext());

app.use('/', api);
```

Where is `api` defined? Why not just:

```js
app.use(awsServerlessExpressMiddleware.eventContext());
```

Which is how you're defining your other middleware.

**Comment by wooooooak** [comment]
@brettstack 
Sorry for confusing.
I import my router like this.
`import api from './router';`
and also i tried to 
`api.use(awsServerlessExpressMiddleware.eventContext());`
and
`api.use(awsServerlessExpressMiddleware.eventContext());`

but both did't work.

**Comment by brettstack** [comment]
Shouldn't you be defining all your middleware the same way though? See our example here:

https://github.com/awslabs/aws-serverless-express/blob/master/examples/basic-starter/app.js#L21

**Comment by wooooooak** [comment]
@brettstack
Right.  Anyway, all other middleware except this are work well. And all router is works well too only except some router using req.apiGateway.

eventContext() function doses't make an error but req.apiGateway object is undefined. It is very weird.

**Comment by brettstack** [comment]
What I'm suggesting is try to change all of your other middleware to use `api.use`.

Just to make sure: are you running this locally or in Lambda? If it's local, you'll need to do some additional work to get the middleware to work.

**Comment by brettstack** [comment]
Also, try logging `console.log(JSON.stringify(req.headers, null, 4))` and seeing if 'x-apigateway-event' is present.

**Comment by wooooooak** [comment]
@brettstack 
x-apigateway-event' is present but req.apiGateway is still undefined In lambda.

**Comment by brettstack** [comment]
I think I'm going to need to see more code. Specifically, the route where you're trying to access `req.headers` and `req.apiGateway`.

As you can see, the middleware is very simple https://github.com/awslabs/aws-serverless-express/blob/master/src/middleware.js#L6. If `x-apigateway-event` is present and `req.apiGateway` is not, then it seems like the middleware isn't being run. Have you tried what I suggested before?

> What I'm suggesting is try to change all of your other middleware to use api.use

**Comment by brettstack** [comment]
Did you manage to solve your issue?

**Comment by wooooooak** [comment]
No. I didn't...

**Comment by bassemfg** [comment]
I found queryStringParameters, pathParameters, stageVariables, requestContext all get passed to the lambda function inside req.headers['x-apigateway-event'] by the proxy API Gateway

**Comment by tomas-optus** [comment]
I found solution for similar problem in a comment here: https://stackoverflow.com/a/42441810/747834

> "app.use(awsServerlessExpressMiddleware.eventContext())" must be done before any "app.use('/', index);"

**Comment by cjander18** [comment]
In case any other lost souls who are encountering `Missing x-apigateway-event or x-apigateway-context header(s)` when doing local testing (e.g. from Postman) find their way here... You have to set one or both of the `x-apigateway-event` and/or `x-apigateway-context` headers in Postman. The important thing is their values have to be 
```
encodeURIComponent(JSON.stringify({"example": "data here" }));
```

So for instance, if the header key is:
```x-apigateway-event```
Then the value should be 
```%7B%22data%22%3A%22Sand%22%2C%22public_key%22%3A%22key%22%7D```

Note, there are no quotes around the encoded and stringified value!

**Comment by adham-123** [comment]
`aws-serverless-express` library is being deprecated and moving to vendia. Here is how it should be done using vendia library



```
const { getCurrentInvoke } = require('@vendia/serverless-express')

app.get('/', (req, res) => {
  const { event, context } = getCurrentInvoke()

  res.json(event)
})
```

Guide: https://github.com/vendia/serverless-express#accessing-the-event-and-context-objects

Source: https://www.npmjs.com/package/aws-serverless-express#:~:text=AWS%20Serverless%20Express%20library%20is%20moving%20to%20Vendia%20and%20will%20be%20rebranded%20to%20serverless-express.%20Similarly%2C%20the%20aws-serverless-express%20NPM%20package%20will%20be%20deprecated%20in%20favor%20of%20a%20new%20serverless-express%20package
