### ISSUE TITLE
Couldn't get a file descriptor referring to the console

### ISSUE THREAD

**Issue by vkkis93** [awslabs/aws-serverless-express#2]
Hello,
When I run command **npm run setup** on step 

> `aws cloudformation create-stack --stack-name`

I always get error _**Couldn't get a file descriptor referring to the console**_

How I can fix it ?

**Comment by vkkis93** [comment]
I found solution:
My OS: Centos 7.1
In package.json in section scripts we have command **create-stack**

> .. open https://console.aws.amazon.com/cloudformation/home?region=$npm_package_config_region

And this command **open** it's npm package which does not work
Two ways how you can fix it
1) Install package **opn-cli** _npm install --global opn-cli_ and change command **open** on **opn**
2) If you use CentOS or you have installed **xdg-open** you can change on command **xdg-open**

**Comment by brettstack** [comment]
Thanks, see #1 also. Since this is the second report of the open command throwing an error, I will remove it.
