### ISSUE TITLE
 errorMessage": "awsServerlessExpressMiddleware.createServer is not a function",

### ISSUE THREAD

**Issue by gsaireddy** [awslabs/aws-serverless-express#205]
[index.zip.zip](https://github.com/awslabs/aws-serverless-express/files/2711000/index.zip.zip)

  i uploaded my code here. i'm facing this issue when i hit the request from api gateway to this lambda function

**Comment by MuthaheerMohammed** [comment]
**use require('aws-serverless-express')**

> awsServerlessExpress = require('aws-serverless-express')
> const express = require('express')
> const app = express()
> 
> const server = awsServerlessExpress.createServer(app)
> exports.handler = (event, context) => { awsServerlessExpress.proxy(server, event, context) }
> 
> app.get('/',function(req,res){
>     res.json("Hello World")
> })
