### ISSUE TITLE
502 Bad Gateway. What should I do?

### ISSUE THREAD

**Issue by jiankafei** [awslabs/aws-serverless-express#206]
502 Bad Gateway.
My project is vue spa app.
What should I do?

```js
'use strict';
process.env.NODE_ENV = 'production';
const awsServerlessExpress = require('aws-serverless-express');
const app = require('./app');
const binaryMimeTypes = [
	'application/octet-stream',
	'font/eot',
	'font/opentype',
	'font/otf',
	'image/jpeg',
	'image/png',
	'image/svg+xml'
];
const server = awsServerlessExpress.createServer(app, null, binaryMimeTypes);
exports.handler = (event, context) => {
  // context.callbackWaitsForEmptyEventLoop = false;
  return awsServerlessExpress.proxy(server, event, context, 'PROMISE').promise;
};
```

**Comment by Can-Sahin** [comment]
if its getting timeouts (which you can see in cloudwatch logs) turn on ` // context.callbackWaitsForEmptyEventLoop = false;
` line. You might have connection left open so that lambda cannot finish, but waits it forever

**Comment by novemberde** [comment]
I suggest you deploying your vue spa app using Amazon S3 with Static Web Site hosting.

https://www.jforte.me/2018/03/deploy-a-vue-js-app-with-aws-s3/

Otherwise, deploy your app using nuxt.js.

Here's the referencce repository.
https://github.com/jeehyukwon/nuxt-serverless

**Comment by TylorShin** [comment]
1. If you want to use async handler, the function should be async function with promise resolver.
```
// current
exports.handler = (event, context) => {
  // context.callbackWaitsForEmptyEventLoop = false;
  return awsServerlessExpress.proxy(server, event, context, 'PROMISE').promise;
};

// suggestion
exports.handler = async (event, context) => {
  // context.callbackWaitsForEmptyEventLoop = false;
  return awsServerlessExpress.proxy(server, event, context, 'PROMISE').promise;
};
```
2. You should set 'text/html' to your `binaryMimeTypes ` to serve gzipped content. (If you're using compression middleware)
