### ISSUE TITLE
Using in end-to-end test doesn't exit process

### ISSUE THREAD

**Issue by petermorlion** [awslabs/aws-serverless-express#209]
Maybe this is because of a lack of understanding on my side, but here's my issue. I have a AWS Lambda function that uses aws-serverless-express. I also have automated end-to-end tests that call my handler directly.

Simplified, my handler looks like this (I'm using Typescript):

```
import * as awsServerlessExpress from "aws-serverless-express";
import { app } from "./app";

const server = awsServerlessExpress.createServer(app);

export function handler(event: AWSLambda.APIGatewayEvent, context: AWSLambda.Context) {
    awsServerlessExpress.proxy(server, event, context);
}
```

In my tests, I call the handler like this:

```
import { handler } from "../../src/handler";

// ....

return new Promise((resolve, reject) => {
        const awsContext: Context = {
            callbackWaitsForEmptyEventLoop: true,
            functionName: "",
            functionVersion: "",
            invokedFunctionArn: "",
            memoryLimitInMB: 128,
            awsRequestId: "cucumber-test",
            logGroupName: "",
            logStreamName: "",
            getRemainingTimeInMillis: () => 1000,
            done: (error?: Error, result?: any) => {
                if (error) {
                    return reject(error);
                }

                resolve(result);
            },
            fail: (error: Error | string) => {
                reject(error);
            },
            succeed: (message: string | any, object?: any) => {
                resolve(message);
            }
        };

        handler(apiGatewayProxyEvent, awsContext);
    });
```

My tests all run green, but the process never exits. I've tried returning the result of the `proxy` call, and also tried calling `done` on my aws context. None seem to change the fact that the process keeps running. I've also tried updating from my 3.1.3 to 3.3.5. Didn't work either. As a final option, I tried exporting the server and calling server.close(). No luck there.

So is it possible to call the handler, which spins up aws-serverless-express, but then have it exit when the processing is done?

**Comment by brettstack** [comment]
Check out the tests in this repo. It's likely that you just need to close the server https://github.com/awslabs/aws-serverless-express/blob/master/__tests__/integration.js#L456

**Comment by petermorlion** [comment]
Sorry for not updating this. Thanks for the tip, it helped. I changed my handler to return the result of the proxy call:

```
return awsServerlessExpress.proxy(server, event, context);
```

Then in my test code:

```
// export the server
export let server: any = null;

...

// export the function to call from tests
export async function callHandler(options: TestEventOptions, world: World) {
    const apiGatewayProxyEvent = { ... }

    return new Promise((resolve, reject) => {
        const awsContext: Context = {
            ...
            done: (error?: Error, result?: any) => {
                if (error) {
                    return reject(error);
                }

                resolve(result);
            },
            fail: (error: Error | string) => {
                reject(error);
            },
            succeed: (message: string | any, object?: any) => {
                resolve(message);
            }
        };

        server = handler(apiGatewayProxyEvent, awsContext);
    });
}
```

Then in an AfterAll hook of my tests (I'm using cucumberjs):

```
import { server } from "../support/callHandler";
...
AfterAll(function() {
    if (server) {
        server.close();
    }
});
```

**Comment by bfeister** [comment]
I have similar code `if (server) { server.close() }` in my tests `afterEach` but when upgrading to `@vendia/serverless-express@^4` I'm getting

```
TypeError: server.close is not a function
```

**Comment by bfeister** [comment]
I have similar code `if (server) { server.close() }` in my tests afterEach but when upgrading to @vendia/serverless-express@^4 I'm getting this... any thoughts @brettstack  @danvendia ?

```
TypeError: server.close is not a function
```
