### ISSUE TITLE
application/json body limitation

### ISSUE THREAD

**Issue by rc9** [awslabs/aws-serverless-express#210]
I'm fairly new to express so forgive me if the question is naive.

Given this [line](https://github.com/awslabs/aws-serverless-express/blob/master/src/index.js#L25) I'm under the impression that ALL requests coming into the application must be either stringified or base64 encoded.
Is this correct? What's the reasoning behind not allowing json in the body of the request as so many apps expect? The response doesn't seem to have this limitation which makes me question such a limitation even more.

**Comment by Nogbit** [comment]
By default, `application/json` is `utf-8`.  So that line you link to indicates that json will work as input.

**Comment by brettstack** [comment]
When you make HTTP requests you need to stringify your JSON. Your Express layer can then automatically parse that back to a JSON object for you https://github.com/awslabs/aws-serverless-express/blob/master/examples/basic-starter/app.js#L22
