### ISSUE TITLE
req.originalUrl will not guarantee URI is exactly the same as incoming requests

### ISSUE THREAD

**Issue by skylinezum** [awslabs/aws-serverless-express#23]
Hi,

A webhook that I'm listening to signs requests with the entire path + queryString.
However, `req.originalUrl` does not guarantee that the exact same URI string is accessible by my lambda functions because `getPathWithQueryStringParams`: https://github.com/awslabs/aws-serverless-express/blob/61d34f075d193e2b6ee83adbb9e6dfd45db4b98e/index.js#L18-L26 is reconstructing queryString from an object of params, so the order of my queryString is not identical to the signed request. This would require API Gateway to pass the raw URI in the context, but I don't see anything here http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#context-variable-reference that would allow it. This may not be doable with the current API Gateway, but it would be a good fix to keep in mind.

Thanks

**Comment by vitalii-budkevych** [comment]
Hello, 
 
Thank you for bringing this up. You're correct that getting url with query params in the original order is not currently possible in the API Gateway backend. API Gateway team will consider adding raw url property for this purpose in future.

**Comment by stoufa06** [comment]
@vitalii-budkevych  Will be there any updates about this issue any time soon?
