### ISSUE TITLE
TypeError: params.context.succeed is not a function

### ISSUE THREAD

**Issue by Vadorequest** [awslabs/aws-serverless-express#230]
I am working on a custom lambda runtime layer for node 6.10.3 and testing it against one of my app that uses aws-serverless-express 3.3.6 (I was using 3.1.3 and just upgraded to see if it would fix anything, but no luck there)

Here is the exception on AWS Lambda:

```
/var/task/node_modules/aws-serverless-express/src/index.js:243
      if (params.resolutionMode === 'CONTEXT_SUCCEED') return params.context.succeed(params2.response)
                                                                             ^
TypeError: params.context.succeed is not a function
    at Object.succeed (/var/task/node_modules/aws-serverless-express/src/index.js:243:78)
    at IncomingMessage.response.on.on (/var/task/node_modules/aws-serverless-express/src/index.js:105:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Here is my implementation:

`src/functions/server/server.js` > this is my Lambda handler `handler: src/functions/server/server.handler`
```js
import es from 'aws-serverless-express';

import { failure } from '../../utils/browserResponse';

const server = es.createServer(require('./app'));

export async function handler(event, context, callback) {
  try {
    return es.proxy(server, event, context);
  } catch (e) {
    callback(null, await failure({ status: false }, e));
  }
}
```

`src/functions/server/app.js` (simplified)
```js
import express from 'express';
import next from 'next';
import proxy from 'express-http-proxy';
import RequestProxy from 'http-proxy';
import bodyParser from 'body-parser';
import awsServerlessExpressMiddleware from 'aws-serverless-express/middleware';

/*
  Middlewares
 */

/**
 * Allow access from lambda to API Gateway event
 * See https://github.com/awslabs/aws-serverless-express#getting-the-api-gateway-event-object
 */
app.use(awsServerlessExpressMiddleware.eventContext());

/**
 * Parses json and only looks at requests where the Content-Type header matches the type option.
 * https://www.npmjs.com/package/body-parser#bodyparserjsonoptions
 */
app.use(bodyParser.json());

app.get('/status', (req, res) => {
  try {
    res.status(200).json({
      status: 'running',
      infrastructure: process.env.IS_OFFLINE ? 'localhost' : 'aws',
      node_env: process.env.NODE_ENV,
      env: process.env.ENV,
      serverTime: moment().format('YYYY-MM-DD HH:mm:ss'),
      timeISO: moment().toISOString(),
      version: process.versions,
      ...getHeadersUsefulData(req.apiGateway.event),
    }, null, 2);
  } catch (e) {
    console.error(e);
  }
});

module.exports = app;

```

It looks like it's somehow calling a non-existing function that is deprecated. I don't quite understand what's the issue at hand here nor how to resolve it. It looks like there is a way to use the callback way instead of the context.succeed but I haven't found how.

Here is my custom runtime ARN if that helps: https://github.com/UnlyEd/aws-lambda-node-runtime-v6.10.3

**Comment by Vadorequest** [comment]
As far as I understand, the error comes from this particular line
https://github.com/awslabs/aws-serverless-express/blob/86c0c58009f26b57f319d9d5089fd1a1cf86ce06/src/index.js#L200

Since I'm using the following: `return es.proxy(server, event, context);` it automatically selects the `CONTEXT_SUCCEED` resolution mode, which seems to fail on my runtime for some reason.

**Comment by brettstack** [comment]
I'm not too familiar with creating custom runtimes, but it sounds like you're missing a `succeed` method on `context` (which I assume you define as part of your runtime). Also, you can specify the `resolutionMode` https://github.com/awslabs/aws-serverless-express/blob/master/__tests__/integration.js#L217-L220

**Comment by Vadorequest** [comment]
I have no idea what the `context` refers to, I assumed it's something related to node itself?

Indeed it looks like I can override the resolutionMode... I thought it was hardcoded line 200.

**Comment by Vadorequest** [comment]
Thanks @brettstack, I changed my implementation to the following

```js
export async function handler(event, context, callback) {
  try {
    return es.proxy(server, event, context, 'CALLBACK', callback);
  } catch (e) {
    callback(null, await failure({ status: false }, e));
  }
}
```

And it worked! :)
