### ISSUE TITLE
Regression when using AWS Lambda custom runtime with "TypeError: params.context.succeed is not a function"

### ISSUE THREAD

**Issue by Vadorequest** [awslabs/aws-serverless-express#231]
I've encountered an issue while migrating from AWS Lambda native runtime `nodejs6.10` to a custom (AKA "provided") runtime of my own.

The `aws-serverless-express` relies on `context.succeed` which is something provided natively by AWS Lambda native nodejs runtimes, but wasn't provided by my custom runtime.

The following behaves differently whether running using AWS Lambda native:
```js
import es from 'aws-serverless-express';
import RavenLambdaWrapper from 'serverless-sentry-lib';
import Raven from 'raven';

import { failure } from '../../utils/browserResponse';

const server = es.createServer(require('./app'));

export async function handler(event, context, callback) {
  try {
    return RavenLambdaWrapper.handler(Raven, es.proxy(server, event, context));
  } catch (e) {
    callback(null, await failure({ status: false }, e));
  }
}
```

The above example works fine when using `runtime: nodejs6.10` but fails when using `runtime: provided`.

---

# In-depth

Using the following in `serverless.yml` will throw `TypeError: params.context.succeed is not a function`
```yml
provider:
  name: aws
  runtime: provided
  # + configure lambda to use a custom runtime ARN
```

Related to https://github.com/awslabs/aws-serverless-express/issues/230 

I'm using this custom runtime: https://github.com/Vadorequest/node-custom-lambda/blob/master/v6.10.3/bootstrap.js (v6.10.3)

I eventually found https://gist.github.com/awerlang/44a994bba14ebf2a62d90be74ee4e67a which seems to be what AWS uses as Lambda runtime (not sure, but looks like it!)

The reference to `context.succeed` can be found there indeed:
```js
        succeed : function(data) {
            checkExpectedArgRange('succeed', arguments, 0, 1);
            context.done(null, data);
        },
```

---

I do not know if anything can be done by `aws-serverless-express`, I suggest to reference this very particular issue in the README to give some heads-up for people using custom runtimes. I've spent about 8h trying to figure the root cause.

**Comment by crowecawcaw** [comment]
I ran into a similar problem. I got around the issue by specifying the resolutionMode as 'PROMISE' for the makeResolver function in src/index.js . The feature wasn't documented that I saw but the following code works for me:

```js
const awsServerlessExpress = require('aws-serverless-express')
const app = require('./src/express')
const server = awsServerlessExpress.createServer(app)

exports.handler = (event, context) => {
  return awsServerlessExpress.proxy(server, event, context, 'PROMISE').promise
}
```

**Comment by Vadorequest** [comment]
Indeed, I finally figured out something similar, using `callback` option.

```js
import es from 'aws-serverless-express';
import { createLogger } from '@unly/utils-simple-logger';
import epsagon from 'epsagon';
import RavenLambdaWrapper from 'serverless-sentry-lib';
import Raven from 'raven';

const server = es.createServer(require('./app'));
const logger = createLogger({
  label: 'Handler',
});

epsagon.init({
  token: process.env.EPSAGON_TOKEN,
  appName: process.env.EPSAGON_APP,
  metadataOnly: false,
});

module.exports.handler = (event, context, callback) => {
  const logGroup = `[${event.httpMethod}] ${event.path}${event.queryStringParameters ? '?' + map(event.queryStringParameters, (v, k) => `${k}=${v}`) : ''}`;
  logger.info(logGroup, `handler`);

  // XXX Callback is required using custom runtime
  //  The default approach is using content.succeed which has been removed in node 8
  const _handler = RavenLambdaWrapper.handler(Raven, es.proxy(server, event, context, 'CALLBACK', callback));

  // XXX Don't use epsagon for /status route (health checks) to reduce cost and avoid noise
  return (event.path === '/status' ? _handler : epsagon.lambdaWrapper(_handler));
};

```
