### ISSUE TITLE
Server swagger UI from basic template?

### ISSUE THREAD

**Issue by jamesmorgan** [awslabs/aws-serverless-express#235]
Hi, we have used your example project to bootstrap our project but now when trying to serve our the API swagger docs we always the following response:
```
HTTP: 403

{
	"message": "Forbidden"
}
```

Our code looks like this:
```
app.use('/docs', swaggerUi.serve, swaggerUi.setup(require('./src/swaggerDocs.yaml')));
```

It works locally but when deploying we also get a 403 Forbidden? I believe it is to do with either the API gateway or the cloud formation scripts, maybe not allowing the response type? But its very hard to know what is causing the error. 

Any ideas on how to solve this?

Thanks

**Comment by brettstack** [comment]
Do you have a basic Hello World page working first? Check the CloudWatch Logs for both your Lambda Function and API Gateway for any errors.

The API Gateway Developer Portal serves Swagger UI. Maybe look into that project for clues.

**Comment by manjeshpv** [comment]
This page isn’t workinglocalhost redirected you too many times.
[Try deleting your cookies](https://support.google.com/chrome?p=rl_error&hl=en-GB).
ERR_TOO_MANY_REDIRECTS
