### ISSUE TITLE
mongodb change streams

### ISSUE THREAD

**Issue by samikarak** [awslabs/aws-serverless-express#244]
My current express app does watch a change-stream of a mongodb connection. There are some special change-stream events, which are triggering some functions to index some data into elasticsearch. The problem is, that the change-stream triggers my watcher after the route call, when express has responded to the request, which does freeze my lambda instance until the next call. (so it is uncertain when my data gets indexed into elasticsearch)

I need a solution to manually call the end of the request, so I can wait until my data is indexed. Any ideas about this ?

**Comment by brettstack** [comment]
You should be able to do something like this in your handler

```js
exports.handler = async (event, context) => {
const response = await awsServerlessExpress.proxy(app, event, context, 'PROMISE').promise
await additionalAsyncStuffHere()
return response
}

```

**Comment by samikarak** [comment]
thank you, I will look into that
