### ISSUE TITLE
Endpoint request timed out.

### ISSUE THREAD

**Issue by prasann** [awslabs/aws-serverless-express#269]
This might not be an issue per se. But I'm not finding any docs related to setting up DB connection using `aws-serverless-express`. So thought someone can help me out here.

I forked it from the [example](https://github.com/awslabs/aws-serverless-express/tree/master/examples/basic-starter]) 

`lambda.js`
```js
'use strict'
let app = require('./dist/app');
const awsServerlessExpress = require('aws-serverless-express');
// binaryMimeTypes Same as that of the example.
const server = awsServerlessExpress.createServer(app, null, binaryMimeTypes);
exports.handler = (event, context) => awsServerlessExpress.proxy(server, event, context);
```

`app.ts`
```ts
const app = (async function () {
    const expressApp = express();
    console.log("Created Express app !!");
    expressApp.use(awsServerlessExpressMiddleware.eventContext());
    console.log("About to create DB..");
    await createConnection(config);
    console.log("Done creating DB !!");
    expressApp.use('/api/user', usersRouter);
    expressApp.use('/', function (req, res) {
        return res.send({user: "John"})
    });
    console.log("Done initializing !!");
    return expressApp;
});
module.exports = app;
```
I have removed the imports to cut down the code. Hope most of them are self-explanatory.

Now, when i try to make a call to the endpoint `/` I'm getting 
```json 
{"message": "Endpoint request timed out"}
```

These are the sequence of logs i see in cloudwatch console.

```
START RequestId ...
INFO Created Express app !!
INFO About to create DB..
INFO Done creating DB !!
INFO Done initializing !!
END RequestId ...
REPORT RequestId ...
Task timed out 
```

I was hoping for my json to be returned. But no luck. Any help is much appreciated.

**Comment by davidmrnustik** [comment]
@prasann  Try make `exports.handler` as async function:
```
exports.handler = async (event, context) => awsServerlessExpress.proxy(server, event, context);
```

**Comment by prasann** [comment]
Thanks @davidmrnustik 
I tried setting up it as `async` but no luck. May be it's an issue in my end.  Will investigate and update my findings.
Thanks for the reply.
