### ISSUE TITLE
HTTP Server Options

### ISSUE THREAD

**Issue by fernandesyuri** [awslabs/aws-serverless-express#272]
I'm facing an issue using aws-serverless-express with my application. Because of new node versions, http request headers are limited to 8KB, and I need more than this. According to the Node documentation, I'm able to increase this limit by passing an options object to the http createServer method, with the "maxHeaderSize" property, but aws-serverless-express won't let me do this, as It's createServer method doesn't expect an options object.

**Comment by jgcmarins** [comment]
check [serverless-http](https://github.com/dougmoscrop/serverless-http) as suggested in #271

**Comment by fernandesyuri** [comment]
> check [serverless-http](https://github.com/dougmoscrop/serverless-http) as suggested in #271

I'm doing some tests with serverless-http and It's working nicely, but I can't figure out why aws-serverless-express won't let us to pass an options object to Node's http server. Wouldn't it be interesting to leave this option free for the user to define?
