### ISSUE TITLE
lambda CloudWatch Errors

### ISSUE THREAD

**Issue by adrai** [awslabs/aws-serverless-express#29]
When using https://github.com/claudiajs/claudia-api-builder each error in the lambda function resulted in an error metric in CloudWatch...
Is there a possibility to do something similar here?

**Comment by brettstack** [comment]
Maybe @gojko could submit a PR...

**Comment by brettstack** [comment]
Since this is always used with API Gateway which logs 4xx and 5xx metrics, how useful is it to log those in aws-serverless-express also?

**Comment by adrai** [comment]
ohhh, sorry. no need for this anymore.
I’ll close it.
