### ISSUE TITLE
AWS Websocket Support

### ISSUE THREAD

**Issue by ethoman** [awslabs/aws-serverless-express#319]
does this work with websockets? Specifically, can I use the AWS Api Gateway websocket with this? If so, how can it be done

**Comment by ethoman** [comment]
never mind, works exactly like http by making a route and grabbing the event as per the readme

**Comment by badpenguin** [comment]
> never mind, works exactly like http by making a route and grabbing the event as per the readme

Do you have an example? I can't get the websocket to reach the ws.on('connection') event.
