### ISSUE TITLE
Where did @types/aws-serverless-express go?

### ISSUE THREAD

**Issue by abecks** [awslabs/aws-serverless-express#330]
It looks the types aren't included with @vendia/serverless-express by default, so I'm just wondering how I would go about installing the TypeScript types for this package now.

**Comment by brettstack** [comment]
This is likely due to the package being renamed to @vendia/serverless-express. Maybe @threesquared @jcaffey, @mattmeye, or @albertovasquez can help? They're listed in the credits for https://www.npmjs.com/package/@types/aws-serverless-express

**Comment by brettstack** [comment]
Added basic Typescript definitions in v4

**Comment by schealex** [comment]
there are still no types in this project right?! Where are we supposed to get those?
