### ISSUE TITLE
npm install fails in example

### ISSUE THREAD

**Issue by raghubansh** [awslabs/aws-serverless-express#333]
Instructions given in Readme are not working. `npm install` fails for `basic-starter-api-gateway-v1` example. Possibly because of this line 
`"@vendia/serverless-express": "file:vendia-serverless-express-4.0.0-rc.2.tgz",`
in dependencies.

**Comment by raghubansh** [comment]
Not able to go past `npm run setup` lol. After looking at other examples, I went past the previous hurdle by changing dependency to `"file:../.."`. Now its complaining about too many levels of nesting for `./src` folder.
`Unable to upload artifact ./src referenced by CodeUri parameter of ExpressLambdaFunction resource.`
`[Errno 40] Too many levels of symbolic links: '/home/raghu/Desktop/Code/serverless-express/examples/basic-starter-api-gateway-v1/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/...`

**Update**
Looks like `npm install --prefix ./src` in the `setup` script option is the culprit. Just running `npm package-deploy` worked.

**Comment by brettstack** [comment]
Sorry, they're referencing the local file. Remove the "@vendia/serverless-express" line from your package.json and run `npm i @vendia/serverless-express`. I'll update examples

**Comment by brettstack** [comment]
Examples fixed
