### ISSUE TITLE
Please publish PR #26 to npm - API Gateway proxy integration decodes URL parameters

### ISSUE THREAD

**Issue by anieve01** [awslabs/aws-serverless-express#34]
My API is broken without this merge. URLs with spaces in the query strings just don't work without this.  I can't complete the migration of production to serverless without PR #26.   How soon can npm be updated with this change?? Thanks.

**Comment by brettstack** [comment]
Sorry, I thought I published this to npm. Best option for now is to point
your dependency at the repo, instead of npm. I'll get it published in the
new year.

**Comment by anieve01** [comment]
Sounds good.  Thank you.

**Comment by brettstack** [comment]
This was published to NPM a while back; closing.
