### ISSUE TITLE
Is there support for HTTP API Gateway?

### ISSUE THREAD

**Issue by afern247** [awslabs/aws-serverless-express#348]
I see in the description this is for REST, so I wonder if HTTP is also supported. 
Also do you guys have any videos?

**Comment by brettstack** [comment]
Yes, the v4 release includes support for HTTP API and more. Check out the example here https://github.com/vendia/serverless-express/tree/mainline/examples/basic-starter-api-gateway-v2

**Comment by brettstack** [comment]
Lmk if you encounter any issues and I'll fix ASAP since this is newly supported.
