### ISSUE TITLE
npm run setup creates error in application dependacies

### ISSUE THREAD

**Issue by athinimafu** [awslabs/aws-serverless-express#349]
I am following guideline given in `vendia/serverless-express/examples/basic-starter-gateway-api-v1`.

guidline specifies to call `npm run setup` when i've set `s3BucketName` and `region` in the package.json config

when i run `npm run setup` the following error occurs
`Unable to upload artifact ./src referenced by CodeUri parameter of ExpressLambdaFunction resource.
[Errno 40] Too many levels of symbolic links: '/home/uncle-shaggy/programs/projects/wufu/chat-server/serverless-express/examples/basic-starter-api-gateway-v1/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example/src/node_modules/@vendia/serverless-express-example'`

`npm run setup` in the package.json scripts object is as follows `"setup": "npm install && npm install --prefix ./src ./ && (cross-var aws s3api get-bucket-location --bucket $npm_package_config_s3BucketName --region $npm_package_config_region || npm run create-bucket) && npm run package-deploy"`

**Comment by brettstack** [comment]
Hi @athinimafu I just pushed the fix for that. You'll want to `rm -rf node_modules && rm -rf src/node_modules` from within the `vendia/serverless-express/examples/basic-starter-gateway-api-v1` directory before running `npm run setup`.

**Comment by athinimafu** [comment]
Thank you at @brettstack that solved the bug.

**Comment by ZPetrovich** [comment]
@brett-vendia Issue is still there even after fix!
