### ISSUE TITLE
how enable compression (gzip)?

### ISSUE THREAD

**Issue by miguelslemos** [awslabs/aws-serverless-express#35]
Hello,  how enable compression, i added compression library

```
app.use(compression());
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(awsServerlessExpressMiddleware.eventContext());
```

added too Accept-Encoding to request

the response is 

```
{ 'x-powered-by': 'Express',
     'access-control-allow-origin': '*',
     'content-type': 'application/json; charset=utf-8',
     'content-length': '331',
     etag: 'W/"14b-aAEboC6Fi//N5cLk6Fl9hQ"',
     vary: 'Accept-Encoding',
     date: 'Mon, 02 Jan 2017 17:59:22 GMT',
     connection: 'close' }
```
why the response doesn't contains?

`Content-Encoding: gzip`

**Comment by kahouieong** [comment]
Currently, this framework doesn't support binary data in request and response.

**Comment by pablobcb** [comment]
is it some gateway api restriction or its related to the actual implementation itself?

gateway api is now supporting binary data, but I cant find anything related to gzip yet.. (besides lots of requests from users on AWS forums)

**Comment by brettstack** [comment]
This is an API Gateway limitation which we will address in the future.

**Comment by brettstack** [comment]
GZIP support added in #51
