### ISSUE TITLE
Headers are not being returned to Api Gateway V2

### ISSUE THREAD

**Issue by seawatts** [awslabs/aws-serverless-express#352]
I am trying to return a `location` header for a `302` redirect. However, after looking at the response headers from API Gateway there doesn't seem to be any headers being sent back. Looking at the code it looks like it converts it back to `multiValueHeaders` [here](https://github.com/vendia/serverless-express/blob/mainline/src/event-sources/aws/api-gateway-v2.js#L60-L67). Looking at the [AWS docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html
) for API Gateway v2 it looks like it should just be returned as `headers` and not `multiValueHeaders`

If I'm missing something please let me know. Otherwise, if this is the issue I'd be happy to send a PR out quickly. 

I'm using `@vendia/serverless-express: 4.0.0-rc.8`

**Comment by brettstack** [comment]
Thanks for the report! I've fixed this in 4.0.0-rc.9. Let me know if there are any other issues.

**Comment by seawatts** [comment]
Thanks for the fast turn around! I'll try it out tonight and report back.

**Comment by seawatts** [comment]
Yup, that did the trick! Thanks again @brettstack 😄
