### ISSUE TITLE
Example api-gw v2 - not working correctly - base url downloads gzip file in browser ?

### ISSUE THREAD

**Issue by muhammedhaque** [awslabs/aws-serverless-express#353]
Hi,

I am running the example as is from the repo - api gw v2  Latest from master

Everytime i try the base url (index) - it is downloading a gzip file.

Can this be looked at it pls :)

**Comment by brett-vendia** [comment]
What browser are you using? I'll try and repro tomorrow.

**Comment by muhammedhaque** [comment]
Hi,

Chrome / Safari - tries to download file
Firefox - displays some mis-encoded text

thanks

**Comment by brettstack** [comment]
I was able to reproduce by removing the `binaryMimeTypes` from the example. If you add those back, this will work. What's happening here is the `compression` middleware is gzipping this. I'll work on improving this to automatically detect and base64 encode a binary response if you don't provide binaryMimeTypes.

**Comment by brettstack** [comment]
Added in v4.0.0-rc.11
