### ISSUE TITLE
Cookies not working in api-gateway-v2

### ISSUE THREAD

**Issue by WarFox** [awslabs/aws-serverless-express#355]
## Thanks!
Firstly, thank you for making this happen. 

The example `examples/basic-starter-api-gateway-v2` works great and now redirection headers are working as well with `rc.10`. Getting redirection was imported for our OAuth2 redirections. Thanks again for fixing headers.

## Problem
I've noticed that `/cookie` url is not working with api gateway v2 example.

```javascript
router.get("/cookie", (req, res) => {
  res.cookie("Foo", "bar");
  res.cookie("Fizz", "buzz");
  res.json({});
});
```

I'm getting a 500 interval server error
```sh
➜ http https://apiid.execute-api.eu-west-1.amazonaws.com/cookie
HTTP/1.1 500 Internal Server Error
Apigw-Requestid: Z2Xssg2yjoEEMaw=
Connection: keep-alive
Content-Length: 35
Content-Type: application/json
Date: Thu, 28 Jan 2021 07:50:15 GMT

{
    "message": "Internal Server Error"
}
```

## Function log
This is what I can see in the Lambda function log

```
2021-01-28T07:26:43.246Z	fe0687d2-745e-476c-bc9f-02bee07fd1fd	DEBUG
{  message: 'SERVERLESS_EXPRESS:FORWARD_RESPONSE:EVENT_SOURCE_RESPONSE',
  successResponse: {    statusCode: 200,
    body: 'e30=',
    headers: [Object: null prototype] {      'x-powered-by': 'Express',
      'access-control-allow-origin': '*',
      'set-cookie': [Array],
      'content-type': 'application/json; charset=utf-8',
      'content-length': '2',
      etag: 'W/"2-vyGp6PvFo4RvsFtPoIWeCReyIC8"',
      vary: 'Accept-Encoding'    },
    isBase64Encoded: true  }}

```

I'm not an expert in API V2, However looking at the documentation [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html), it seems the problem is because `set-cookie` is an Array

Possible fix is to move `set-cookie` array outside of `headers` and put it in `cookies` array instead
```json
{
    "cookies" : ["cookie1", "cookie2"],
    "isBase64Encoded": true|false,
    "statusCode": httpStatusCode,
    "headers": { "headerName": "headerValue", ... },
    "body": "Hello from Lambda!"
}    
```

**Comment by brett-vendia** [comment]
Thanks! I'll fix that asap. Docs here https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

**Comment by WarFox** [comment]
great! thanks @brett-vendia 

I have tested this theory manually in a patched version and have deployed the example for v2

```sh
➜ 😃 http https://qf25bo7aff.execute-api.eu-west-1.amazonaws.com/cookie
HTTP/1.1 200 OK
Apigw-Requestid: Z2iRGhP2DoEEPUg=
Connection: keep-alive
Content-Length: 2
Content-Type: application/json; charset=utf-8
Date: Thu, 28 Jan 2021 09:02:25 GMT
X-Powered-By: Express
etag: W/"2-vyGp6PvFo4RvsFtPoIWeCReyIC8"
set-cookie: Foo=bar; Path=/
set-cookie: Fizz=buzz; Path=/
vary: Accept-Encoding

{}
```

Here's a PR for that fix, if it helps! https://github.com/vendia/serverless-express/pull/356

**Comment by brett-vendia** [comment]
Merged. Thanks!
