### ISSUE TITLE
No exported member 'getCurrentInvoke'.

### ISSUE THREAD

**Issue by michaelmerrill** [awslabs/aws-serverless-express#359]
`import { configure, getCurrentInvoke } from '@vendia/serverless-express';`

When trying to access `getCurrentInvoke` I'm getting the following error.

`Module '"../node_modules/@vendia/serverless-express/src"' has no exported member 'getCurrentInvoke'.`

```(javascript)
// index.js

const configure = require('./configure')
const { getCurrentInvoke } = require('./current-invoke')

module.exports = configure
module.exports.getCurrentInvoke = getCurrentInvoke
```

**Comment by michaelmerrill** [comment]
I was importing incorrectly. should be
`import serverlessExpress, {
  getCurrentInvoke,
} from '@vendia/serverless-express';`

**Comment by brettstack** [comment]
Out of curiosity, how were you importing when you got the error?

**Comment by michaelmerrill** [comment]
I was importing like this:

```(javascript)
import { configure, getCurrentInvoke } from '@vendia/serverless-express';
```
But I should have known better looking at the source. 

```(javascript)
module.exports = configure                                                      // only available as default
module.exports.getCurrentInvoke = getCurrentInvoke.         // only available as destructured property
```

**Comment by abecks** [comment]
I am seeing this error on 4.3.1, when using imports with TypeScript:

```js
import serverlessExpress, { getCurrentInvoke } from '@vendia/serverless-express'
```

`TS2305: Module '"../node_modules/@vendia/serverless-express/src"' has no exported member 'getCurrentInvoke'.`

**Comment by brettstack** [comment]
@abecks could you send a PR to fix that?
