### ISSUE TITLE
[BUG] package-function doesn't remove deleted files

### ISSUE THREAD

**Issue by miguelslemos** [awslabs/aws-serverless-express#36]
Hello guys, I faced a problem when I deleted a file that already uploaded, the package-function only  add new and update old files, but if you delete a file, you must delete lambda-function.zip before compress a new lambda-function.zip 

just update package-function to

``` "package-function": "zip -FSr -q -r lambda-function.zip lambda.js app.js index.html node_modules",```

**Comment by brettstack** [comment]
Thanks for the report. We will soon be updating the example to use
Serverless Application Model (SAM) which will resolve this issue.

**Comment by miguelslemos** [comment]
@brettstack any idea when be released?

**Comment by brettstack** [comment]
I cant give a date, but it's making its way towards the top of my list. :)

**Comment by brettstack** [comment]
Added SAM in #40
