### ISSUE TITLE
How to upgrade to 4.x ?

### ISSUE THREAD

**Issue by j0k3r** [awslabs/aws-serverless-express#360]
As the 4.x is a major release and no `UPGRADE.md` file exist in the repo, I was wondering how should we upgrade from the 3.4.0 version ?

**Comment by brettstack** [comment]
Thanks! Added https://github.com/vendia/serverless-express/blob/mainline/UPGRADE.md

**Comment by brettstack** [comment]
Let me know if you have encounter any issues :)

**Comment by j0k3r** [comment]
Great, thanks!
We were using that method to speedup warm function:

```js
import serverlessExpress from '@vendia/serverless-express'
import app from 'src/app'
import configureApp from 'src/configureApp'

// global variable server to keep hot in lambda
// server is set at the first call and reused then
let server

export default async (event, context) => {
  if (server) {
    return serverlessExpress.proxy(server, event, context, 'PROMISE').promise
  }

  console.log('Server does not exist')

  try {
    // init dbs connexion, middleware and other stuff
    await configureApp(app)
  } catch (e) {
    console.error(e)
  }

  // other initialization

  server = serverlessExpress.createServer(app)

  return serverlessExpress.proxy(server, event, context, 'PROMISE').promise
}
```

It looks like it's a bit more complicated now that we can't init the server and pass `event` & `context` later?

**Comment by brettstack** [comment]
You should be able to do something like this https://github.com/vendia/serverless-express/issues/351#issuecomment-768096594

**Comment by j0k3r** [comment]
It worked. Thanks

I used:

```js
import serverlessExpress from '@vendia/serverless-express'
import app from 'src/app'
import configureApp from 'src/configureApp'

// global variable server to keep hot in lambda
// server is set at the first call and reused then
let server

export default async (event, context) => {
  if (server) {
    return server(event, context)
  }

  console.log('Server does not exist')

  try {
    // init dbs connexion, middleware and other stuff
    await configureApp(app)
  } catch (e) {
    console.error(e)
  }

  // other initialization

  server = serverlessExpress({ app }).handler

  return server(event, context)
}
```

An other question we do have a lot of debug message now which are quite huge (it killed a chrome tab just to try to view it on Cloudwatch):
![image](https://user-images.githubusercontent.com/62333/106603156-38d8de00-655e-11eb-8625-f8e63eb05831.png)

How can we disable them?

**Comment by brettstack** [comment]
Ahh good point. Originally this was using Winston and would only log when `NODE_ENV === 'development'`. I'll get a fix out, but you do also have the option of providing your own `log` object https://github.com/vendia/serverless-express#log

**Comment by brettstack** [comment]
I've pushed a patch that at least doesn't log debug for production builds. Will get something better in soon to allow setting log.level without needing to specify the other log methods

**Comment by j0k3r** [comment]
Thanks, finally used that snippet and it worked as expected!

```js
import serverlessExpress from '@vendia/serverless-express'
import app from 'src/app'
import configureApp from 'src/configureApp'

// global variable server to keep hot in lambda
// server is set at the first call and reused then
let server

export default async (event, context) => {
  if (server) {
    return server(event, context)
  }

  console.log('Server does not exist')

  try {
    // init dbs connexion, middleware and other stuff
    await configureApp(app)
  } catch (e) {
    console.error(e)
  }

  // other initialization

  server = serverlessExpress({ app })

  return server(event, context)
}
```

**Comment by sudhirjena** [comment]
@j0k3r - Could you please share the a code snippet for `configureApp`. I am also running into a similar issue but unsure what your `configureApp` does?

**Comment by j0k3r** [comment]
@sudhirjena Here is a short version:

```js
import app from './app'

app.set('isProduction', process.env.NODE_ENV === 'prod')
app.set('json spaces', 2)

export default (application) => {
  application.set('app:ready', true)

  return application
}
```

And `app.js`:

```js
import express from 'express'

process.env.TZ = 'Europe/Paris'

export default express()
```
