### ISSUE TITLE
Unit test example

### ISSUE THREAD

**Issue by tniemann** [awslabs/aws-serverless-express#363]
Hi,

could I add an example how to start a unit test?

I have this simple test and it failed with "**Error: Unable to determine event source based on event.**"
```

'use strict';

const app = require('../../build/lambda');
var event, context;

describe('Tests index', function () {
    it('verifies successful response', async () => {
        const result = await app.handler(event, context)

        expect(result).to.be.an('object');
    });
});

```

Thx

**Comment by brettstack** [comment]
You need to provide an event object like for the event source you're using (API Gateway v1/v2, ALB, Edge) https://github.com/vendia/serverless-express/blob/mainline/jest-helpers/api-gateway-v1-event.js#L4-L138. This lib can be helpful there, though sometimes limiting https://github.com/serverless/aws-event-mocks

**Comment by thetumper** [comment]
> You need to provide an event object like for the event source you're using (API Gateway v1/v2, ALB, Edge) https://github.com/vendia/serverless-express/blob/mainline/jest-helpers/api-gateway-v1-event.js#L4-L138. This lib can be helpful there, though sometimes limiting https://github.com/serverless/aws-event-mocks

I don't see any ALB event there.  :(
