### ISSUE TITLE
Unable to determine event source for sam-cli local HttpApi

### ISSUE THREAD

**Issue by jrr** [awslabs/aws-serverless-express#368]
I'm using AWS SAM's [local](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-start-api.html) tooling, executing dockerized lambdas with e.g. `sam local start-api`.

This has worked fine with serverless-express until I switched our template's events from [Type:Api](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html) to [Type:HttpApi](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html). Once I did, I started getting this error:

```
2021-02-11T04:28:57.207Z	97815557-f566-49b0-acb3-2dd92f315d34	ERROR	Invoke Error 	
{"errorType":"Error",
"errorMessage":"Unable to determine event source based on event.",
"stack":["Error: Unable to determine event source based on event.",
"    at getEventSourceNameBasedOnEvent (/var/task/node_modules/@vendia/serverless-express/src/event-sources/utils.js:79:9)",
"    at proxy (/var/task/node_modules/@vendia/serverless-express/src/proxy.js:26:21)",
"    at configureProxy (/var/task/node_modules/@vendia/serverless-express/src/configure.js:29:14)",
"    at Runtime.configureHandler [as handler] (/var/task/node_modules/@vendia/serverless-express/src/configure.js:43:61)",
"    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}
```

Here's the event as reported by `sam local start-api --debug`:

```json
{
  "version": "2.0",
  "routeKey": "GET /",
  "rawPath": "/",
  "rawQueryString": "",
  "cookies": [],
  "headers": {
    "Host": "localhost:9000",
    "User-Agent": "curl/7.64.1",
    "Accept": "*/*",
    "X-Forwarded-Proto": "http",
    "X-Forwarded-Port": "9000"
  },
  "queryStringParameters": {},
  "requestContext": {
    "accountId": "123456789012",
    "apiId": "1234567890",
    "http": {
      "method": "GET",
      "path": "/",
      "protocol": "HTTP/1.1",
      "sourceIp": "127.0.0.1",
      "userAgent": "Custom User Agent String"
    },
    "requestId": "aacf57f7-2fce-4069-a1f2-7cb4726dc028",
    "routeKey": "GET /",
    "stage": null
  },
  "body": "",
  "pathParameters": {},
  "stageVariables": null,
  "isBase64Encoded": false
}
```

Notice in particular that `stage` is _null_.

Here's the responsible code in serverless-express:
https://github.com/vendia/serverless-express/blob/0ecd5150db5f40c065ac8435f900695836188363/src/event-sources/utils.js#L74-L76

I'm not sure if the null stage behavior is unique to the sam local environment, or if this could also happen with events in deployed lambdas.

Do you recall why the `&& event.requestContext.stage` clause is in there? Would the code correctly cover existing cases if it were changed to something like this?:

```js
  if (event.requestContext && event.requestContext.elb) return 'AWS_ALB'
  if (event.Records) return 'AWS_LAMBDA_EDGE'
  if (event.requestContext) {
    return event.version === '2.0' ? 'AWS_API_GATEWAY_V2' : 'AWS_API_GATEWAY_V1'
  }
```

(moving AWS_LAMBDA_EDGE up, and removing the check for .stage)

This fixes it for me, but I don't want to break it for anyone else. I'll open a PR if this seems like a good approach.

**Comment by brettstack** [comment]
Thanks for the report! Yes this should be enough. A PR would be great! 🙂
