### ISSUE TITLE
Fail to get binary data.

### ISSUE THREAD

**Issue by skatpgusskat** [awslabs/aws-serverless-express#39]
(Region : ap-northeast-2, seoul)

### What I did
1. Set API Gateway Binary Support, case of Conetent-type : application/octet-stream.
2. Add binary types parameter on ```createServer``` from ```aws-serverless-express```
3. Set request header ```Accept``` with ```application/octet-stream```.
4. Send binary data like ```res.send(data);```. I checked ```isBase64Encoded``` is ```true```.

### What I expected
I expected to got binary data that decoded by api gateway

### What I actually got
I got base64 encoded values.

And also, when I revert commit b61d288 , I could get binary data.

What's wrong with me?

**Comment by skatpgusskat** [comment]
And I found that there are no option ```isBase64Encoded``` in Output Format of a Lambda Function for Proxy Integration

[In this doc](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html), the Output Format is like below
`
{
    "statusCode": httpStatusCode,
    "headers": { "headerName": "headerValue", ... },
    "body": "..."
}
`

**Comment by skatpgusskat** [comment]
@jjappi , @kahouieong 
Review this issue please.

**Comment by skatpgusskat** [comment]
I think we should decode from input of API Gateway, not encode output data.

**Comment by jjappi** [comment]
It's true that isBase64Encoded flag is not documented for output but it's discussed e.g. here: https://forums.aws.amazon.com/thread.jspa?messageID=759454

"For the Lambda proxy case, you can send the base64 encoded flag with your response from Lambda to tell API Gateway if your response body is base64 encoded, however, you need to send an Accept header which is defined in the binaryMediaTypes in order to receive a binary response from API Gateway"

**Comment by skatpgusskat** [comment]
@jjappi oh, you are my hero. I was looking forward some documentations or posts! I think I set wrong option on api gateway. So I close this issue.

**Comment by dinvlad** [comment]
Sorry for reviving the thread, but is `isBase64Encoded` supposed to be set only for truly binary responses (such as images and data)? I'm trying to return gzipped `application/json`, and I see that it's returned with `isBase64Encoded: true`, and base64-encoded in my client response as well. This prevents me from using standard tools for decompression (e.g. Curl). Or perhaps I misunderstood how that works?

Thanks

**Comment by brettstack** [comment]
If it's still base64-encoded when you get a response from the client, you need to configure your API's binary mime types (from console: Click your API then click Binary Support on the left; add your mime types or */* and deploy your API).

**Comment by dfloresgonz** [comment]
@samikarak Did you solve it?

**Comment by brettstack** [comment]
Don't do this `res.setHeader('isBase64Encoded')`.
