### ISSUE TITLE
Relationship between this project and the Serverless framework?

### ISSUE THREAD

**Issue by glasser** [awslabs/aws-serverless-express#396]
I'm trying to understand whether there's a relationship between this project and https://github.com/serverless/serverless

I think the answer is no, but it might be great if the README mentioned that explicitly?

(Context: I'm a maintainer of [Apollo Server](https://github.com/apollographql/apollo-server). We provide a way to serve GraphQL with a bunch of different web frameworks. This includes Express and our own direct implementation for Lambda. We've found ourselves having to essentially reimplement a lot of Express/middleware features in our implementation. It would be great if we could just use something like `serverless-express` to let us convert our full Express implementation into a Lambda implementation, and allow our users to extend their server with standard Express middleware.  We would use `serverless-express` as purely an implementation detail wrapped inside our `apollo-server-lambda` package.  We would want this to work for everyone, not just people using a particular deployment methodology like https://github.com/serverless/serverless . I'm pretty sure that your project will work fine for this use case; is that right?)

**Comment by brettstack** [comment]
This project is unrelated to Serverless Framework. They use this package as the implementation of their own Express offering and apollo-server should be able to do the same.

**Comment by glasser** [comment]
Thanks!
