### ISSUE TITLE
aws profile option

### ISSUE THREAD

**Issue by jeonghwan-kim** [awslabs/aws-serverless-express#4]
Thanks for awesome project that I expected.

I suggest that there should be a way to setup specific profile data. (profile is defined in `~/.aws/config`)

For example:
```
npm run config <accountId> <bucketName> [region] [profileName]
```

**Comment by egut** [comment]
I set the profile before by: export AWS_DEFALT_PROFILE=<aws profile name> in bash.

So to do it with the config option add aws_profile to the config hash (default name: default)
Then add --profile=$aws_profile to all aws-commands.

**Comment by brettstack** [comment]
The commands provided in the example can be used as a base for you to modify however you choose. For now we want to keep it as simple as possible, and expect you will modify to suit your needs (as @egut mentions).

**Comment by jeonghwan-kim** [comment]
@egut @brettstack thanks for answer
