### ISSUE TITLE
Please add support to Facebook chatbot

### ISSUE THREAD

**Issue by snehav27** [awslabs/aws-serverless-express#43]
```
const successResponse = {statusCode, body, headers, isBase64Encoded}

            context.succeed(successResponse)
```

I have written chatbot with node.js and express. And I have pushed it Heroku which works fine. But now when I want move to lambda function, it needs this node_module to support express.

Facebook chatbot expects only body with hub.challenge field in int format but in this code it sends all the response which facebook webhook doesnt allow it expects hub.challenge number.
Please help or let me know if there is any other package doing the same since this package wont work.

**Comment by brettstack** [comment]
Can you provide example of what Facebook chatbot expects, and what is being sent by Lambda/API Gateway/Express?
