### ISSUE TITLE
Outdated docs? 

### ISSUE THREAD

**Issue by ImreC** [awslabs/aws-serverless-express#440]
Quick question. From the docs I read:

> resolutionMode (default: 'PROMISE')

> Lambda supports three methods to end the execution and return a result: context, callback, and promise. By default, serverless-express uses promise resolution, but you can specify 'CONTEXT' or 'CALLBACK' if you need to change this. If you specify 'CALLBACK', then context.callbackWaitsForEmptyEventLoop = false is also set for you.

I want to set `context.callbackWaitsForEmptyEventLoop = false`, but `resolutionMode` seems not to be defined on the `serverlessExpress` type. Is there a different way to do this now? Is there something else I should do/not do to make this work?

**Comment by jarredkenny** [comment]
The types in this package are severely lacking compared to the actual JS implemetation. 

I've gotten around this by defining my own `ConfigureParams` interface and doing `serverless({app} as unknown as MyConfigureParams)` but its not a great solution.

This should really be reopened.
