### ISSUE TITLE
Difficult to configure custom event source

### ISSUE THREAD

**Issue by mikejpeters** [awslabs/aws-serverless-express#466]
Hi, thanks for the great library! 

I'm using serverless-express v4.3.11 and am trying to support AWS schedule events in addition to the standard gateway events.

The relevant part of my `serverless.yml` file:

```yml
functions:
  endpoints:
    handler: main.handler
    events:
      - http:
          path: /{any+}
          method: ANY
      - schedule:
          rate: rate(1 minute)
```

Based on my understanding of the [docs](https://github.com/vendia/serverless-express/tree/v4.3.11#eventsource) this should be possible by doing something like this:

```js
serverlessExpress({
  app,
  eventSource: {
    getRequest: requestMapper,
    getResponse: responseMapper,
  },
});

function requestMapper({ event }) {
  if (event.requestContext) {
    // AWS API gateway event
    const apiGatewayEventSource = eventSources.getEventSource({
      eventSourceName: 'AWS_API_GATEWAY_V1',
    });
    return apiGatewayEventSource.getRequest({ event });
  } else {
    // AWS schedule event
    return {
      method: 'get',
      path: 'schedule',
      headers: {},
    };
  }
}
```

But [`getEventSourceNameBasedOnEvent()`](https://github.com/vendia/serverless-express/blob/6adac653fe1daf1dd44ff6aa17dbf08f07662173/src/event-sources/utils.js#L70-L80) throws the error `Unable to determine event source based on event.`.

Am I missing something? I can override `eventSourceName` in the options to always return a string, but that seems a bit hacky and that option is not included in the Typescript typings.

I also am currently importing `eventSources` from `@vendia/serverless-express/src/event-sources` in order to still support the standard events, but that seems fragile since it's not part of the public API.

IMO it would be great if:

- It wasn't necessary to override both `eventSourceName` and `eventSource` in order to support custom events
- It was possible to add support for an event source (e.g. AWS schedule) without losing the default implementation

I can take a shot at creating a pull request, but I wanted to first confirm with you whether this makes sense. 

Thanks!

**Comment by aedenmurray** [comment]
Agreed, or expose `eventSources` as part of the public API.

**Comment by adlecluse** [comment]
Hi @mikejpeters how did you make it work eventually? And got rid of this `Unable to determine event source based on event.` error?
I'm having similar issue for handling SQS in my case.

**Comment by mikejpeters** [comment]
@adlecluse I ended up not really needing custom events, but if I remember correctly you also have to pass a custom `eventSourceName` function in your `serverlessExpress` configuration:

```js
serverlessExpress({
  app,
  eventSource: {
    getRequest: requestMapper,
    getResponse: responseMapper,
  },
  eventSourceName: getEventSourceName
});
```

For reference the built-in event source name function is here:
https://github.com/vendia/serverless-express/blob/276a6da64d22acec931dc0d567993f1e1f65597f/src/event-sources/utils.js#L70-L89

**Comment by adlecluse** [comment]
Thanks, will try it later if I need SQS again. 
For now I used SNS as it was natively supported in this package.

**Comment by iheffernan** [comment]
Any further updates on this? 

I'm looking to extend with support for EventBridge events, but I also would like to handle the standard supported event types, i.e. a request to my Lambda could come from API Gateway V1, API Gateway V2, OR EventBridge. If it comes from APIGW v1 or v2, I just want to let serverless-express do it's normal mapping. Only if I detect it to be EventBridge to I do my custom mapping.

Pseudo-code...

```javascript
if (event.detail-type && event.source) {
    // handle EventBridge event
} else {
    // do standard eventSource handling
}
```

Thanks...
