### ISSUE TITLE
Reusing the Database connection in app

### ISSUE THREAD

**Issue by PrathameshTM** [awslabs/aws-serverless-express#481]
I am not sure how things work with [this example](https://github.com/vendia/serverless-express/blob/mainline/examples/basic-starter-api-gateway-v2/src/lambda-async-setup.js).
How does the database connection object become available in the app?

More detailed question [here](https://stackoverflow.com/questions/70265030/reusing-the-database-connection-object-with-vendia-serverless-express).

**Comment by H4ad** [comment]
If you use Typeorm, you can connect to your database in one place and get the connection elsewhere using [getConnection()](https://orkhan.gitbook.io/typeorm/docs/connection-api), so you don't need to directly pass your connection to the app.

But, in this example, you can create whithin `./app` a method to initialize your database, pass it to your express instance to build your routes, and then return your express instance to be used to create `serverlessExpress({ app })`.

Something like this:

```javascript
async function setup (event, context) {
  const expressApp= await app.initializeExpressInstanceWithDatabase()

  serverlessExpressInstance = serverlessExpress({ app: expressApp })
  return serverlessExpressInstance(event, context)
}
```

**Comment by bneigher** [comment]
RDS proxy can be leveraged here as a secondary measure.  It can help manage/reuse db connections.
