### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by amrut123456789** [awslabs/aws-serverless-express#482]
getting below error after converting nodejs project into aws lambda using this library.

PayloadTooLargeError: request entity too large

**Code =>**
'use strict'
const awsServerlessExpress = require('aws-serverless-express')
const app = require('./server/server')
const binaryMimeTypes = [
	'application/octet-stream',
	'font/eot',
	'font/opentype',
	'font/otf',
	'image/jpeg',
	'image/png',
	'image/svg+xml'
]
const server = awsServerlessExpress.createServer(app, null, binaryMimeTypes);
exports.handler = (event, context) => awsServerlessExpress.proxy(server, event, context)

Please suggests whats the issue.

**Comment by H4ad** [comment]
Are you sending a file larger than 10MB? If so, you may be hitting in the API Gateway limits, see more at [AWS API Gateway Limits](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html).

If you need to save files in S3, i recommend that you use [s3 presigned post](https://www.webiny.com/blog/upload-files-to-aws-s3-using-pre-signed-post-data-and-a-lambda-function-7a9fb06d56c1), this will allow you to upload large files (more than 10mb) on S3 directly from the client.

**Comment by piyushk96** [comment]
I'm getting the same error but my file size is around 3-4 MB. Also, I'm using ALB for triggering the lambda function

**Comment by H4ad** [comment]
Accords [the docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html), more than 1MB you trigger the limits and receive an error.
