### ISSUE TITLE
lambda gives "Unable to determine event source based on event." while calling from CloudWatch events

### ISSUE THREAD

**Issue by ravishankar82** [awslabs/aws-serverless-express#490]
While we invoke my lambda from CloudWatch Event and wanted to forward the call to '/' get path.
but its not forwarding the call to app.js

Here is my sample code

`const serverlessExpress = require('@vendia/serverless-express')`
 `const expApp = require('./app')`
 `return serverlessExpress({ app: expApp })(event, context);`

**Comment by H4ad** [comment]
This library does not support cloudwatch event as an event source (yet, see [this PR](https://github.com/vendia/serverless-express/pull/477)).

What you can do is create your own event source to handle cloudwatch events, like [as this documentation explains](https://github.com/vendia/serverless-express#eventsource) based on the PR of cnuss, the code of what you need to put in the `getRequest` and `getResponse` you can get from [this file](https://github.com/vendia/serverless-express/blob/b5da6070b8dd2fb674c1f7035dd7edfef1dc83a2/src/event-sources/aws/eventbridge.js).

**Comment by ravishankar82** [comment]
Thanks for quick response.
