### ISSUE TITLE
Error on setup typescript example

### ISSUE THREAD

**Issue by primemb** [awslabs/aws-serverless-express#494]
when i try build typescript example i get this error : 

```
> basic-starter-api-gateway-v2-typescript@2.1.1 sam:deploy
> cross-var sam deploy --stack-name $npm_package_config_cloudFormationStackName --capabilities CAPABILITY_IAM --s3-bucket $npm_package_config_s3BucketName --s3-prefix $npm_package_name --parameter-overrides DomainName=$npm_package_config_domain --region $npm_package_config_region --no-fail-on-empty-changeset

Error: Invalid value for '--parameter-overrides':  DomainName= is not in valid format. It must look something like 'ParameterKey=KeyPairName,ParameterValue=MyKey ParameterKey=InstanceType,ParameterValue=t1.micro' or 'KeyPairName=MyKey InstanceType=t1.micro'
```

my config : 

```
  "config": {
    "s3BucketName": "my-app-sls",
    "region": "us-east-1",
    "cloudFormationStackName": "ServerlessExpressTypeScriptStack",
    "functionName": "",
    "domain": ""
  }
```

**Comment by H4ad** [comment]
You can't deploy the sam stack without passing valid `domain` and `functionName`.

**Comment by primemb** [comment]
> You can't deploy the sam stack without passing valid `domain` and `functionName`.

I used the same config for normal javascript one (without typescript) and it worked fine I only have this problem when I use typescript also I want use the default AWS API link for now and get domain later

**Comment by H4ad** [comment]
Try with this command: `cross-var sam deploy --stack-name $npm_package_config_cloudFormationStackName --capabilities CAPABILITY_IAM --s3-bucket $npm_package_config_s3BucketName --s3-prefix $npm_package_name --region $npm_package_config_region --no-fail-on-empty-changeset --parameter-overrides DomainName=$npm_package_config_domain`

I put the `--parameter-overrides` at the end, maybe it recognizing the other parameters as input.

You can try too putting single quotes in the `'DomainName=$npm_package_config_domain'`

**Comment by primemb** [comment]
fixed thank you

**Comment by KaminoRyo** [comment]
Hi, I am also encountering the same situation.

> You can try too putting single quotes in the 'DomainName=$npm_package_config_domain'

I solved it with this.
