### ISSUE TITLE
Unclear as to how getCurrentInvoke is supposed to work?

### ISSUE THREAD

**Issue by tkambler** [awslabs/aws-serverless-express#509]
I'm new to @vendia/serverless-express, and I'm trying to understand how the following example from the README can possibly work:

```
const { getCurrentInvoke } = require('@vendia/serverless-express')
app.get('/', (req, res) => {
  const { event, context } = getCurrentInvoke()
  res.json(event)
})
```

If the Lambda function running your application is warm, and a number of concurrent connections are received and processed by the same Lambda instance, then how is it that a call to `getCurrentInvoke()` returns information about _that request's_ invocation rather than a subsequent one that has since come in and is now also being processed (prior to the current one completing)?

**Comment by H4ad** [comment]
Lambda only handles one request at a time, so when we call `setCurrentInvoke` before forwarding the request to your framework, we are guaranteed that the return from `getCurrentInvoke` will be the same as what you defined with `setCurrentInvoke` for that request.

On the next request, `setCurrentInvoke` will overwrite the old data from the last request (if the function is still warm) and then process the request with the same strategy.
