### ISSUE TITLE
4.7.0 Broke my build

### ISSUE THREAD

**Issue by danxgh10** [awslabs/aws-serverless-express#512]
It broke when deploying and trying to do an npm install. I fixed by setting version to strict what I have in my package.json

npm info run @vendia/serverless-express@4.7.0 preinstall node_modules/@vendia/serverless-express npx npm-force-resolutions  
npm info run @vendia/serverless-express@4.7.0 preinstall { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 991ms     
npm timing reify:rollback:retireShallow Completed in 0ms      
npm timing command:i Completed in 12162ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\Users\daniel\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:394:28)  
npm verb stack     at maybeClose (node:internal/child_process:1064:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm verb pkgid @vendia/serverless-express@4.7.0
npm verb Windows_NT 10.0.19044
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\daniel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "--verbose"
npm verb node v16.8.0
npm verb npm  v8.4.1
npm ERR! code 1
npm ERR! path ...\node_modules\@vendia\serverless-express
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npx npm-force-resolutions
npm ERR! npm verb cli [
npm ERR! npm verb cli   'C:\\Program Files\\nodejs\\node.exe',npm ERR! npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm ERR! npm verb cli   'prefix',
npm ERR! npm verb cli   '-g'
npm ERR! npm verb cli ]
npm ERR! npm info using npm@7.21.0
npm ERR! npm info using node@v16.8.0
npm ERR! npm timing npm:load:whichnode Completed in 0ms       
npm ERR! npm timing config:load:defaults Completed in 1ms     
npm ERR! npm timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 1ms
npm ERR! npm timing config:load:builtin Completed in 1ms      
npm ERR! npm timing config:load:cli Completed in 2ms
npm ERR! npm timing config:load:env Completed in 1ms
npm ERR! npm timing config:load:project Completed in 1ms      
npm ERR! npm timing config:load:file:C:\Users\daniel\.npmrc Completed in 0ms
npm ERR! npm timing config:load:user Completed in 0ms
npm ERR! npm timing config:load:file:C:\Users\daniel\AppData\Roaming\npm\etc\npmrc Completed in 0ms
npm ERR! npm timing config:load:global Completed in 0ms       
npm ERR! npm timing config:load:validate Completed in 0ms     
npm ERR! npm timing config:load:credentials Completed in 1ms  
npm ERR! npm timing config:load:setEnvs Completed in 1ms      
npm ERR! npm timing config:load Completed in 9ms
npm ERR! npm timing npm:load:configload Completed in 9ms      
npm ERR! npm timing npm:load:setTitle Completed in 0ms        
npm ERR! npm timing npm:load:setupLog Completed in 0ms        
npm ERR! npm timing config:load:flatten Completed in 3ms      
npm ERR! npm timing npm:load:cleanupLog Completed in 2ms      
npm ERR! npm timing npm:load:configScope Completed in 0ms     
npm ERR! npm timing npm:load:projectScope Completed in 0ms    
npm ERR! npm timing npm:load Completed in 16ms
npm ERR! npm timing command:prefix Completed in 1ms
npm ERR! npm verb exit 0
npm ERR! npm timing npm Completed in 246ms
npm ERR! npm info ok
npm ERR! npm verb cli [
npm ERR! npm verb cli   'C:\\Program Files\\nodejs\\node.exe',npm ERR! npm verb cli   'C:\\Users\\daniel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm ERR! npm verb cli   'exec',
npm ERR! npm verb cli   '--',
npm ERR! npm verb cli   'npm-force-resolutions'
npm ERR! npm verb cli ]

**Comment by brett-vendia** [comment]
Just released 4.7.1 please try
