### ISSUE TITLE
Compatibility with restify?

### ISSUE THREAD

**Issue by anho** [awslabs/aws-serverless-express#54]
Hi,

has anybody tested this library in conjunction with restify instead of express? Is it doable or not?

Best
Andreas

**Comment by kahouieong** [comment]
This library is designed for express, but you can test it with restify.

**Comment by anho** [comment]
Hey, thanks for your prompt response. I'm aware that this library is only designed to work with express. Nevertheless, express and restify share some common concepts, so I thought maybe someone already tried to make it work with restify. If so, it would be interesting - at least for me -  to share some experiences and insights.

**Comment by brettstack** [comment]
This library is designed to be framework-agnostic and should work with any
framework (or plain vanilla Node HTTP). It should work with testify, though
I have not tried it.

**Comment by lfreneda** [comment]
Not clear to me.. Does it work with restify?

**Comment by copperorange** [comment]
Having a little trouble getting this going with Restify and Swagger UI. Works fine in local and docker. Will keep trying but was wandering if anyone else had success.
