### ISSUE TITLE
res.sendFile returning different results when run locally vs in Lambda

### ISSUE THREAD

**Issue by JensenTStava** [awslabs/aws-serverless-express#55]
The below code returns different results based on running it locally vs running it on Lambda. Locally this returns a javascript file properly formatted. However, when I deploy to Lambda I get a base64 encoded blob that is not readable by my application. I have this set up as a proxy integration with API gateway, so it should not be altering the payload at all, and yet it is. Why is this library (or lambda) forcing a base64 encoded response?

```
'use strict'
const path = require('path')
const compression = require('compression')
const express = require('express')
const bodyParser = require('body-parser')
const cors = require('cors')
const awsServerlessExpressMiddleware = require('aws-serverless-express/middleware')
const app = express()


app.set('view engine', 'pug')
app.use(compression())
app.use(cors())
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
app.use(awsServerlessExpressMiddleware.eventContext())

app.get('/widget/:widgetId', (req, res) => {
	console.log(req)
	res.setHeader('Content-Type', 'text/javascript')
    res.sendFile(path.join(__dirname, '/widget/bundle.js'), {}, function (err) {
    	if(err) {
    		console.log(err)
    	} else {
    		console.log("no error")
    	}
    })
})

// app.listen(3000, function () {
//   console.log('Example app listening on port 3000!')
// })

module.exports = app
```

**Comment by brettstack** [comment]
Ensure you have text/javascript configured in your API Gateway API as a binary media type https://github.com/awslabs/aws-serverless-express/blob/master/example/simple-proxy-api.yaml#L98

**Comment by JensenTStava** [comment]
Is there a way to do that in the AWS UI?

**Comment by brettstack** [comment]
Yes, click on your API and then click Binary Support

**Comment by JensenTStava** [comment]
I have tried that. It doesn't convert the output back to non-base64

**Comment by brettstack** [comment]
Did you redeploy your API after setting that?

**Comment by JensenTStava** [comment]
Yes. I have tried everything apparent... been troubleshooting for 4 hours. Is there should me Lambda configuration that isn't apparent?

**Comment by brettstack** [comment]
Only this https://github.com/awslabs/aws-serverless-express/blob/master/example/lambda.js#L23

**Comment by JensenTStava** [comment]
I already have that represented when creating the express server:

`'use strict'
const awsServerlessExpress = require('aws-serverless-express')
const app = require('./app')

const binaryMimeTypes = [
  'text/javascript'
]
const server = awsServerlessExpress.createServer(app, null, binaryMimeTypes)


exports.handle = (event, context) => { 
  console.log("event: " +JSON.stringify(event))
  console.log("context: "+ JSON.stringify(context))
  awsServerlessExpress.proxy(server, event, context) }`

The data is being returned as text/javascript, it is just base64 encoded...

**Comment by JensenTStava** [comment]
Ok. I found the problem. I am using Apex to deploy my code and it seems that there is a requirement to use `exports.handle` as opposed to `exports.handler`. But `module.exports = app` in my express app is not resolving back to `exports.handle`. Is there a way that I can address this?

**Comment by brettstack** [comment]
In your lambda.js you can do `exports.handle = app`.

**Comment by JensenTStava** [comment]
When I make that change I get the following error:

`Error: function response: "listener" argument must be a function`

Upon looking at this further, I cannot understand why this would be returning data at all if the export was misconfigured. The problem is not that my routes are not being respected, it is that the data being returned from my express app is being altered buy Lambda, or this library. Does aws-serverless-express encode the data before sending it to the calling service?

**Comment by kahouieong** [comment]
This library will decode the data from API Gateway and pass in your express application, then encode the data before return it to API Gateway.

**Comment by brettstack** [comment]
@JensenTStava did you resolve this? You could try modifying your API Gateway API Binary types to include `*/*` and then redeploy.
