### ISSUE TITLE
Customize Lambda function name

### ISSUE THREAD

**Issue by guillegette** [awslabs/aws-serverless-express#6]
Hi there, I really can not find a way to change the Lambda function name "AwsServerlessExpressFunction" I was able to change the stack, api endpoint etc. Any ideas? Thanks!

Edit: I should've added that I have updated the function name here https://github.com/awslabs/aws-serverless-express/search?utf8=✓&q=AwsServerlessExpressFunction

**Comment by brettstack** [comment]
Simply perform a find and replace on the example directory before running
setup. We will consider adding this to the config step.

**Comment by brettstack** [comment]
So long as you edited the function name prior to running the setup command, that should work. If it does not work, can you provide more details on the error you're getting?

**Comment by guillegette** [comment]
Hi @brettstack thanks for your response. I did a find/replace of `AwsServerlessExpressFunction` and still the function created had the name `AwsServerlessExpressFunction`. I will start from a scratch with a new project and try again. I do not see any error but the problem is that if you have more than one project then there is a name collision. Will update the ticket once I have more details.

**Comment by brettstack** [comment]
Hi @guillegette did you manage to get this working?
