### ISSUE TITLE
Performance degradation because of logging

### ISSUE THREAD

**Issue by H4ad** [awslabs/aws-serverless-express#613]
I'm the maintainer of [Serverless Adapter](https://github.com/H4ad/serverless-adapter) which was based on this library.

I found an issue on my library in the logging, which I describe in more detail here: https://github.com/H4ad/serverless-adapter/pull/77.

But to resume, this is the CPU Profiling of my library:

![serverless-adapter-old](https://user-images.githubusercontent.com/12551007/210153588-0742c37e-4c28-4b95-a991-ec4bb6f6a778.png)

And because it was based on this library, those lines below are the problem:

https://github.com/vendia/serverless-express/blob/75cfbffeb3fd030695b9587a75300c7b8012ac6a/src/configure.js#L46-L53

Calling `util.inspect` and logging `event` and `context` is very expensive, from my tests, took 3ms.

By just removing, or deferring (which I choose for my library), I improve the performance by 100% and it became very close to the performance of [serverless-http](https://github.com/dougmoscrop/serverless-http).

**Comment by brettstack** [comment]
Thanks @H4ad! I didn't realize `util.inspect` was so expensive. I might opt for just removing it entirely since we know the shape of `context` and `event` and can simply log the important parts. For `logBody`the user can log the full response on their end if needed.

**Comment by H4ad** [comment]
@brettstack We don't necessarily need to remove the entire call, at #614 I just defer the execution of the log.

But if you think that worth it, I could run another benchmark removing the entire `util.inspect` call and leaving just the plain object.
