### ISSUE TITLE
Socket hang up error after 3 sec when calling https.get from within app.get

### ISSUE THREAD

**Issue by dcorns** [awslabs/aws-serverless-express#62]
I have server simple server index.js. I upload the attached zip to lambda. When I run the test to request /allPrizeData I get the error noted above in 2 to 3 seconds. The call back in 'https.get' is never called as demonstrated with the console.log statement. This code executes quickly and correctly locally. The code tests fine on Lambda when I give it mock data to return instead of using the call to https.get in order to retrieve the real data. But as stated, there is no trouble when running locally.
The problem can be duplicated by uploading the attached archive file as the code for a new lambda function, changing the proxy test to get /allPrizeData, and running the test. Note: The url to the data will work for your test as well because it is readable by everyone.
[archive.zip](https://github.com/awslabs/aws-serverless-express/files/952908/archive.zip)

`

**Comment by kahouieong** [comment]
What the timeout do you set on your Lambda function? You can try to increase it to see if it is resolved.

**Comment by dcorns** [comment]
Set for 2min but no change. It fails after 200ms.

**Comment by dcorns** [comment]
{ [Error: socket hang up] code: 'ECONNRESET' }

**Comment by dcorns** [comment]
I went ahead and called the function from api gateway and I get the expected result, however the test fails. Perhaps, this is a problem of the test configuration. Here is the test code.
`{
  "body": "{\"test\":\"body\"}",
  "resource": "/{proxy+}",
  "requestContext": {
    "resourceId": "123456",
    "apiId": "1234567890",
    "resourcePath": "/{proxy+}",
    "httpMethod": "POST",
    "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef",
    "accountId": "123456789012",
    "identity": {
      "apiKey": null,
      "userArn": null,
      "cognitoAuthenticationType": null,
      "caller": null,
      "userAgent": "Custom User Agent String",
      "user": null,
      "cognitoIdentityPoolId": null,
      "cognitoIdentityId": null,
      "cognitoAuthenticationProvider": null,
      "sourceIp": "127.0.0.1",
      "accountId": null
    },
    "stage": "prod"
  },
  "queryStringParameters": {
    "foo": "bar"
  },
  "headers": {
    "Via": "1.1 08f323deadbeefa7af34d5feb414ce27.cloudfront.net (CloudFront)",
    "Accept-Language": "en-US,en;q=0.8",
    "CloudFront-Is-Desktop-Viewer": "true",
    "CloudFront-Is-SmartTV-Viewer": "false",
    "CloudFront-Is-Mobile-Viewer": "false",
    "X-Forwarded-For": "127.0.0.1, 127.0.0.2",
    "CloudFront-Viewer-Country": "US",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Upgrade-Insecure-Requests": "1",
    "X-Forwarded-Port": "443",
    "Host": "1234567890.execute-api.us-east-1.amazonaws.com",
    "X-Forwarded-Proto": "https",
    "X-Amz-Cf-Id": "cDehVQoZnx43VYQb9j2-nvCh-9z396Uhbp027Y2JvkCPNLmGJHqlaA==",
    "CloudFront-Is-Tablet-Viewer": "false",
    "Cache-Control": "max-age=0",
    "User-Agent": "Custom User Agent String",
    "CloudFront-Forwarded-Proto": "https",
    "Accept-Encoding": "gzip, deflate, sdch"
  },
  "pathParameters": {
    "proxy": "path/to/resource"
  },
  "httpMethod": "GET",
  "stageVariables": {
    "baz": "qux"
  },
  "path": "/allPrizeData"
}`

**Comment by dcorns** [comment]
The testing of the proxy calling the function from api gateway also fails. {get} {/allPrizeData}

**Comment by dcorns** [comment]
but again, the actual call to the api gateway yields the expected result.
[api gateway link](https://pjpk6esqw5.execute-api.us-west-2.amazonaws.com/prod/allPrizeDatal)

**Comment by kahouieong** [comment]
Can you turn on the logging for the outgoing request?

**Comment by dcorns** [comment]
Where?

**Comment by kahouieong** [comment]
In your Lambda function code, you can attach a request logging for capture an outgoing request. If you can use the exact same parameter without this framework to connect your firebase endpoint, it will help us a lot on investigate the issue.

**Comment by dcorns** [comment]
Ok, but it is only failing on the lambda test. The function is actually working. I will send the results later.

**Comment by dcorns** [comment]
I checked into the logging, but I am a little unclear on how to put it in the function since it is generated with the archive file that I upload. If you can be more specific, I will do it.(you already have the code, if that is easier) In the mean time here is the log from the test.
START RequestId: 5eef6228-296d-11e7-a832-4d3ea16d9210 Version: $LATEST
2017-04-25T04:12:18.534Z	5eef6228-296d-11e7-a832-4d3ea16d9210	allPrizesCalled
2017-04-25T04:12:18.831Z	5eef6228-296d-11e7-a832-4d3ea16d9210	{ Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9) code: 'ECONNRESET' }
END RequestId: 5eef6228-296d-11e7-a832-4d3ea16d9210
REPORT RequestId: 5eef6228-296d-11e7-a832-4d3ea16d9210	Duration: 629.67 ms	Billed Duration: 700 ms 	Memory Size: 128 MB	Max Memory Used: 25 MB

**Comment by kahouieong** [comment]
You can use [this library](https://www.npmjs.com/package/request-debug) to capture the request, then zip the code and upload to your Lambda function.

**Comment by dcorns** [comment]
ok, will try this tomorrow.

**Comment by dcorns** [comment]
Sorry, I can not help out on this any longer right now, I have some other pressing matters. I will come back to this later, but if you want to close it for now, I understand.

**Comment by 1ststopgroup** [comment]
I have the same error here, does anybody know the solution? Connecting to a db throws all kind of problems but it's fine without db code...

**Comment by dcorns** [comment]
If your using firebase, it is because firebase keeps the socket alive. You cane run firebase connections from a forked child process and terminate it with process.exit, this will then allow the parent process to to close normally.
On May 17, 2017, at 10:39, 1ststopgroup <notifications@github.com<mailto:notifications@github.com>> wrote:

I have the same error here, does anybody know the solution? Connecting to a db throws all kind of problems but it's fine without db code...
