### ISSUE TITLE
Replace the event.path

### ISSUE THREAD

**Issue by throrin19** [awslabs/aws-serverless-express#626]
Hello,
Actually, I use the version v3.4.0 of the `aws-serverless-express` package.

I start research to migrate to the moved package and to the latest version but I don't find an imformation.

Actually, in AWS, I use differents paths for my environment `my-api.host.com/environment` like `my-api.host.com/stage`, `my-api.host.com/v1`, ...

In the v3.4.0, I was doing this with the library to avoid routing problems with express:

```js
exports.handler = (event, context) => {
        // FIXME: Ugly workaround for https://github.com/awslabs/aws-serverless-express/issues/86 and https://github.com/claudiajs/claudia/issues/170
        if (event.path.startsWith('/dev')) {
            event.path = event.path.replace('/dev', '');
        } else if (event.path.startsWith('/stage')) {
            event.path = event.path.replace('/stage', '');
        } else if (event.path.startsWith('/test')) {
            event.path = event.path.replace('/test', '');
        } else if (event.path.startsWith('/v1')) {
            event.path = event.path.replace('/v1', '');
        } else if (event.path.startsWith('/demo')) {
            event.path = event.path.replace('/demo', '');
        }

        return awsServerlessExpress.proxy(server, event, context);
};
```

Have you any method to do this in the v4 version of serverless-express ?

**Comment by thadeu** [comment]
@throrin19 You can use regex to factory this. 

```js
event.path = event.path.replace(/^\/(dev|stage|test|demo|v1)/g, '')
```

More elegant, I guess 😀

**Comment by throrin19** [comment]
@thadeu my bad, after research I show it's made automatically with v4 version
