### ISSUE TITLE
README version update needed

### ISSUE THREAD

**Issue by dpurrington** [awslabs/aws-serverless-express#63]
Under "cons", the README states, "Currently limited to Node.js 4.3 (LTS)." It should be "4.3 and 6.10", although I'm not sure this really even rates as a con anymore. Even if it is, we can say that you can use babel to achieve whatever language features you want.

**Comment by kahouieong** [comment]
We will update the README as long as we verify this library is working with Node.js 6.10

**Comment by dpurrington** [comment]
Just saw the open PR, which makes this issue a dup. Closing.
