### ISSUE TITLE
Why is application/json listed as a binary media type in example project?

### ISSUE THREAD

**Issue by bolddp** [awslabs/aws-serverless-express#64]
Hi!
I've just spent a few hours troubleshooting a strange error I got only when deploying to AWS Lambda / API Gateway, and it turns out that it is because application/json is listed in the binaryMimeTypes collection in your example project. When I removed it, the POST and PATCH calls work just fine.

What is the reason for this, in what scenario are you interested in treating JSON input data as base64?

**Comment by kahouieong** [comment]
The intention was to treat most of the data as binary data not just base64 encoded.

**Comment by bolddp** [comment]
OK, thanks for the info! I was just surprised, because the example didn't seem to work out of the box when I deployed it to AWS Lambda. The following error was thrown when I POSTed JSON data with a Content-Type of application/json. It seems that base64-encoded data is sent to the JSON parser, and I got it to work by removing application/json from binaryMimeTypes in lambda.js and the Swagger YML.

Is this the expected behavior?

> 2017-04-27T13:56:10.467Z	3078a373-2b50-11e7-96c6-a5828501763c	SyntaxError: Unexpected token e in JSON at position 0
at Object.parse (native)
at parse (/var/task/node_modules/body-parser/lib/types/json.js:89:17)
at /var/task/node_modules/body-parser/lib/read.js:116:18
at invokeCallback (/var/task/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
at done (/var/task/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
at IncomingMessage.onEnd (/var/task/node_modules/body-parser/node_modules/raw-body/index.js:307:7)
at emitNone (events.js:86:13)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)

**Comment by kahouieong** [comment]
Can you share your API setting and the request parameters?

**Comment by brettstack** [comment]
It's listed for gzip support. However, there is a bug in the lib where it was not encoding the request correctly. PR submitted.

**Comment by brettstack** [comment]
Released. Please update to version 3.0.0
