### ISSUE TITLE
Fix OpenSSF Scorecard issues

### ISSUE THREAD

**Issue by eran-medan** [awslabs/aws-serverless-express#647]
This (great and super useful) project has a scorecard of 3.1/10 at this time. There are straight forward steps to move the needle up. 

https://deps.dev/npm/%40vendia%2Fserverless-express

Some of these fixes can be done with a PR, but some may need a maintainer. See the details in the link above for remediation.

**Comment by brettstack** [comment]
Thanks! We're making some improvements.
