### ISSUE TITLE
POST body is not in the apiGateway.event

### ISSUE THREAD

**Issue by dpurrington** [awslabs/aws-serverless-express#65]
The body of a POST is not being put into the apiGateway.event object of the request. I'm not sure if you'll consider this a defect or not, but it was surprising that it wasn't there given that it typically is (when not using this package, like when you write a typical lambda).

A simple fix would be to change the middleware to pluck it from the request.body value and put it in request.apiGateway.event.

**Comment by kahouieong** [comment]
Why do you think it is necessary to be able to the request body from request.apiGateway.event? We are hoping the customer puts the express application inside a Lambda function with very minimum modification.

**Comment by dpurrington** [comment]
Ok, I didn't understand that to be the main goal of the package. Now that makes sense. 

Currently, I have handlers written to handle lambda events and I'm retrofitting them to use express, so that's different use case. They expect to find the body in the event. It's easy enough for me to copy the body into that event for their purpose, but I also expect long term to just _expressify_ my existing handler(s).

Thanks for clarifying it.

**Comment by jspooner** [comment]
@kahouieong do you know how POST body is obtained?  

app.js
```
app.post('/', function(req, res) {
  res.send(req.body) // returns ""

```

**Comment by brettstack** [comment]
Should be available as usual, on `req.body`.

**Comment by guerrerocarlos** [comment]
Remember to use `bodyParser.json()` or `bodyParser.urlencoded({ extended: false })` as express middleware to make te body available in the *req* object.
