### ISSUE TITLE
Logger doesn't work

### ISSUE THREAD

**Issue by create1st** [awslabs/aws-serverless-express#651]
The logger function incorrectly assumes that you provide additional information and fails since a call to the logger in debug mode doesn't always carry additional information.
`/Users/create/work/lambda-sns/node_modules/@vendia/serverless-express/src/logger.js:43
        ...additional.map(lazyPrint)
                      ^
TypeError: Cannot read properties of undefined (reading 'map')
    at Object.debug (/Users/create/work/lambda-sns/node_modules/@vendia/serverless-express/src/logger.js:43:23)
    at getFramework (/Users/create/work/lambda-sns/node_modules/@vendia/serverless-express/src/frameworks/index.js:13:9)`

**Comment by anishsam** [comment]
I have around 50 APIs built using @vendia/serverless-express and all of them stopped working suddenly after a redeployment. After spending a day troubleshooting, I found out that the logger.js has been changed in the latest version to use "...additional.map(lazyPrint)". This was causing following error when invoking the API:
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read properties of undefined (reading 'map')",
    "stack": [
        "TypeError: Cannot read properties of undefined (reading 'map')",
        "    at Object.debug (/var/task/node_modules/@vendia/serverless-express/src/logger.js:43:23)",
        "    at getFramework (/var/task/node_modules/@vendia/serverless-express/src/frameworks/index.js:13:9)",
        "    at configure (/var/task/node_modules/@vendia/serverless-express/src/configure.js:22:35)",
        "    at Object.<anonymous> (/var/task/index.js:6:19)",
        "    at Module._compile (node:internal/modules/cjs/loader:1196:14)",
        "    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1074:32)",
        "    at Function.Module._load (node:internal/modules/cjs/loader:909:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1098:19)",
        "    at require (node:internal/modules/cjs/helpers:108:18)"
    ]
}

I will revert back to version 4.10.1 for now, but above error is a blocker issue for the latest version. My lambda hander code is as below:
exports.handler = serverlessExpress({ app, logSettings: { level: "debug" } });

**Comment by brettstack** [comment]
@create1st  @anishsam  thanks for the report. This should be fixed in 4.10.4 thanks to @H4ad

**Comment by anishsam** [comment]
Thank you
