### ISSUE TITLE
Is there support for NodeJS Server from HTTP module

### ISSUE THREAD

**Issue by vorant94** [awslabs/aws-serverless-express#656]
Hi, there!

I am writing a pet project and I want to deploy NodeJS server as a lambda. I see your library does a good job of converting ExpressJS to lambda function. Because other stuff I added to the project I don't run ExpressJS app straightforward, but rather create a server from it like this

```
import http from 'http';

const server = http.createServer(app)

server.listen(...)
```

The question is does this lib support wrapping not only ExpressJS, but http.Server also? And if not, what is your recommendation in my case?

**Comment by brettstack** [comment]
Yes this also works . See https://github.com/vendia/serverless-express/tree/mainline/examples/vanilla-http
