### ISSUE TITLE
can't run nestjs application using SAM

### ISSUE THREAD

**Issue by thedarkknight197** [awslabs/aws-serverless-express#687]
Hi i am using this doc that use your package https://docs.nestjs.com/faq/serverless#example-integration

But when i send a call using sam i receive this error: `2024-08-06T20:21:19.852Z        7ad7a4bd-18a5-4365-9d2b-51239d1c7153    ERROR   Invoke Error    {"errorType":"TypeError","errorMessage":"(0 , serverless_express_1.default) is not a function","stack":["TypeError: (0 , serverless_express_1.default) is not a function","    at bootstrap (/var/task/dist/lambda.js:12:45)","    at async Runtime.handler (/var/task/dist/lambda.js:15:25)"]}`

**Comment by brettstack** [comment]
Could you elaborate on "when i send a call using sam"? It might have something to do with your transpilation. You can try `import { configure as serverlessExpress } from '@codegenie/serverless-express'` instead if it's having a hard time importing the default export.

**Comment by vunguyen464301** [comment]
me too ! how to fix this problem?

**Comment by thedarkknight197** [comment]
@brettstack i confirm that work.

example:
```typescript
import { NestFactory } from '@nestjs/core';
import serverlessExpress from '@codegenie/serverless-express';
import { Callback, Context, Handler } from 'aws-lambda';
import { AppModule } from './app.module';

let server: Handler;

async function bootstrap(): Promise<Handler> {
  const app = await NestFactory.create(AppModule);
  await app.init();

  const expressApp = app.getHttpAdapter().getInstance();
  return serverlessExpress({ app: expressApp });
}

export const handler: Handler = async (
  event: any,
  context: Context,
  callback: Callback,
) => {
  server = server ?? (await bootstrap());
  return server(event, context, callback);
};

```
