### ISSUE TITLE
[Question] Socket.io / Long running connections

### ISSUE THREAD

**Issue by Ninir** [awslabs/aws-serverless-express#7]
Hi everyone,

I was wondering about the way if it could work (or not) if your front is using some kind of socket.io stuff. Is it possible?
I guess the long-running connection is a limitation in this case (since Lambda timeouts).

Thank your for any explanation!

**Comment by brettstack** [comment]
Currently API Gateway does not support Web Sockets, although it is a frequently requested feature which we may support in the future.

**Comment by Ninir** [comment]
Thank you for the quick reply.
Even though API gateway does not support it, wont lambda have a problem with the maximum execution time?

**Comment by brettstack** [comment]
That is correct.

**Comment by Ninir** [comment]
Got it, thank you @brettstack
