### ISSUE TITLE
Impossible to serve HTML larger than 1kB ?

### ISSUE THREAD

**Issue by BerndWessels** [awslabs/aws-serverless-express#73]
It seems to be impossible to serve back HTML larger than 1kB.

No error in the logs but also no response from the APIGateway endpoint.

If you reduce the HTML response string to under 1kB text it magically starts working.

Does anybody know how to fix this?

```js
const app = express();

app.use((req, res, next) => {
  console.log(req.url);
  next();
});

app.disable('x-powered-by');

app.use(compression());

app.use(awsServerlessExpressMiddleware.eventContext());

app.get('*', (req, res, next) => {
    let htmlString = "<html><body>PUT A HTML STRING WITH MORE THAN 1KB TEXT HERE</body></html>";
    res.status(200).send(htmlString);
});

// NOTE: If you get ERR_CONTENT_DECODING_FAILED in your browser, this is likely
// due to a compressed response (e.g. gzip) which has not been handled correctly
// by aws-serverless-express and/or API Gateway. Add the necessary MIME types to
// binaryMimeTypes, and to the x-amazon-apigateway-binary-media-types array in
// simple-proxy-api.yaml, then redeploy (`npm run package-deploy`)
const binaryMimeTypes = [
  // 'application/javascript',
  // 'application/json',
  'application/octet-stream',
  // 'application/xml',
  'font/eot',
  'font/opentype',
  'font/otf',
  'image/jpeg',
  'image/png',
  'image/svg+xml',
  // 'text/comma-separated-values',
  // 'text/css',
  // 'text/html',
  // 'text/javascript',
  // 'text/plain',
  // 'text/text',
  // 'text/xml'
];

// Create the AWS Lambda server.
const server = awsServerlessExpress.createServer(app, null, binaryMimeTypes);

// Export the AWS Lambda server proxy.
exports.handler = (event, context) => awsServerlessExpress.proxy(server, event, context);
```

**Comment by brettstack** [comment]
This is due to gzip which only triggers after 1KB. You need to configure binary data correctly.

Add in text/html to your binaryMimeTypes; ensure text/html is configured on your API Gateway API binary mime types and redeploy.

**Comment by BerndWessels** [comment]
Thanks @brettstack 
Where and how in API Gateway (I'm using the console or terraform) do the mime types have to be configured for that to work?

**Comment by brettstack** [comment]
I'm not familiar with Terraform API. In Console you can click on your API and then click Binary Support in the left side nav. Ensure the list matches what you specify in binaryMimeTypes. Alternatively, specify */* in API Gateway console and list your content types just in your Lambda function. Support for */* in the aws-serverless-express lib is coming #70

**Comment by BerndWessels** [comment]
Thank you @brettstack 

That is working now.

Maybe we can add a more detailed documentation to the README. I'm pretty sure this is a common problem people will run into.

By the way, if the page body is actually less than 1kB, would that still work?

**Comment by brettstack** [comment]
Yes it will continue to work for <1KB.

Agreed, the documentation can be improved. I will do that along with #70.
