### ISSUE TITLE
multipart request,  corrupted files

### ISSUE THREAD

**Issue by hackash** [awslabs/aws-serverless-express#78]
I found this module useful, because I want to handle multipart form data in my lambda function and express framework has a lot or working modules with multipart, I am using [formidable](https://github.com/felixge/node-formidable), which works fine with normal express application, but in case of this, I keep getting corrupted files in some of the reasons.

This happens only for non txt files, txt files are uploaded and rendered properly.
Here is the code snippet that might be useful to reproduce the problem. 

```
   fs.readFile(req.files['file'].path, 'binary', (err, data) => {
        if (err) {
            throw err;
        }
        fs.writeFile('some.[some ext]', data, 'binary', (err, data) => {
            if (err) {
                throw err;
            }
            res.end('OK');
        });
    });
```

After running this, I get the file in my local server , but it is corrupted, so I can't open it. 
e.g images are not being shown, in normal image preview applications
e.g zip files can not be opened via archivers ERROR 21 is not a directory.

can anyone explain the problem ? Thanks in advance .

**Comment by brettstack** [comment]
Are you running this locally with `npm run local` or running your Express app directly? If the former, this may be base64 encoding your responses, but without the API Gateway layer it isn't decoding before getting back to the client.

**Comment by hackash** [comment]
I am using  [serverless-offline](https://github.com/dherault/serverless-offline) on my local machine, to run the lambda. Any ideas ?

**Comment by hackash** [comment]
Seems to be an [issue](https://github.com/dherault/serverless-offline/issues/230) on serverless offline side, I'll investigate it and ping you back, thank you for the answer.

**Comment by brettstack** [comment]
Thanks. Closing for now.
