### ISSUE TITLE
Not able to make a simple project wor

### ISSUE THREAD

**Issue by marcelolfilho** [awslabs/aws-serverless-express#80]
Hi, sorry for such 101 question but I'm kinda new with AWS, NodeJS and Express.

I'm setting up a basic serverless API Gateway:

```
// index.js
import AwsServerlessExpress from 'aws-serverless-express';
import App from './src/app';

const server = AwsServerlessExpress.createServer(App);

exports.handler = (event, context) => AwsServerlessExpress.proxy(server, event, context);
```
```
// ./src/app.js
import Express from 'express';
import BodyParser from 'body-parser';
import AwsServerlessExpressMiddleware from 'aws-serverless-express/middleware';

let app = Express();

app.use(BodyParser.json());
app.use(BodyParser.urlencoded({extended: true}));
app.use(AwsServerlessExpressMiddleware.eventContext());

app.get('/status', (req, res) => {
    res.json({ a: "status" });
});

app.get('/', (req, res) => {
    res.json({ a: "root" });
});

export default app;
```

And on the API Gateway console interface:
![alt text](http://i.imgur.com/r0ZXZE6.png "api config")
![alt text](http://i.imgur.com/Io78V0j.png "method config")
![alt text](http://i.imgur.com/nJcmvxc.png "error")

What's the problem here? If you need more information let me know please.

Thanks.

**Comment by lorenzoaws** [comment]
From your screenshot it looks like your test request is hitting the resource path "/v1". The {proxy+} child resource under v1 needs at least one path component to match successfully. Try adding an additional path component to your test request.
