### ISSUE TITLE
aws-serverless-express with lambda not working

### ISSUE THREAD

**Issue by santhuisland** [awslabs/aws-serverless-express#87]
Hi All,

I am trying sample API for testing node express APi running as aws lambda using aws-serverless-express and deploying to aws APIGateway. all works on local and also works when i deploy using Claudia.

But when i manually deploy without Claudia it throws err.
Example:
1)exporting index.js which contain
'use strict'
const awsServerlessExpress = require('aws-serverless-express')
const app = require('./server')

// NOTE: If you get ERR_CONTENT_DECODING_FAILED in your browser, this is likely
// due to a compressed response (e.g. gzip) which has not been handled correctly
// by aws-serverless-express and/or API Gateway. Add the necessary MIME types to
// binaryMimeTypes below, then redeploy (`npm run package-deploy`)
const binaryMimeTypes = [
  'application/javascript',
  'application/json',
  'application/octet-stream',
  'application/xml',
  'font/eot',
  'font/opentype',
  'font/otf',
  'image/jpeg',
  'image/png',
  'image/svg+xml',
  'text/comma-separated-values',
  'text/css',
  'text/html',
  'text/javascript',
  'text/plain',
  'text/text',
  'text/xml'
]
const server = awsServerlessExpress.createServer(app, null, binaryMimeTypes)

exports.handler = (event, context) => awsServerlessExpress.proxy(server, event, context)

2)./server.js contains simple test api using express framework
piRoutes.get('/test', function(req,res) {
	res.json({ message : 'hooray! welcome to our api!  , http://localhost:' + port + '/api' });
});

3)I have zipped all files with node_modules and granted write/execute permission to the zip
4) uploaded to aws lambda console or s3 bucket
5) then i have configured lambda settings with index.handler and granted all permission to the roles in aws
6)when i trigger the executing lambda through lambda console or through API Gateway it always shows this error ,please check the attached screen shot below

![screen shot 2017-07-20 at 08 43 31](https://user-images.githubusercontent.com/1822741/28406239-99f18a80-6d27-11e7-8171-f1ae831f2591.png)

![screen shot 2017-07-20 at 15 18 44](https://user-images.githubusercontent.com/1822741/28422076-e3183f6a-6d5e-11e7-90a6-fb4e42682b07.png)

7)with the same example if i try without awsServerlessExpress  it works and prints the result
exports.handler = (event, context, callback) => {
    callback(null, 'Hello from Lambda from zip');
}
attached screen shot 
![screen shot 2017-07-20 at 08 48 28](https://user-images.githubusercontent.com/1822741/28406387-497c537c-6d28-11e7-8e2b-4dabfdd16e64.png)

Please suggest the what i am doing wrong with awsServerlessExpress exporting node express API.

Advance thanks
Santhosh

**Comment by brettstack** [comment]
As per the screenshot, the Lambda function is not throwing an error. The body is returning a base64 encoded string, since Lambda does not allow returning Binary. Whether to Base64 encode or not is determined by the `binaryMimeTypes`.

It looks like you are only using part of the example (the handler) but using your own Express app and API Gateway definition; is this accurate?

**Comment by brettstack** [comment]
Just saw the second screenshot with the error, but no explanation of what you are doing different in the 2 scenarios

**Comment by santhuisland** [comment]
Hi Brett,

Thanks for your quick reply.
Here is the full zip which i am uploading to aws lambda console also zip contain LambdaApiGateway.json used to create apigateway and integrate which calling this lambda.
[index.zip](https://github.com/awslabs/aws-serverless-express/files/1164892/index.zip)

here is the postman screen shot which i got when i executed the api
![screen shot 2017-07-21 at 09 20 33](https://user-images.githubusercontent.com/1822741/28455134-e2853796-6df5-11e7-9326-ec0b2ecb5734.png)

Please i am eagerly waiting solution for this.

Thanks for your help
Santhosh

**Comment by brettstack** [comment]
I recommend running the example in this repo first. Once you have that running, try swapping in your own Express app.

**Comment by adamsiwiec** [comment]
This is the exact same issue I am having. Why should we need to use the example? Does it matter whether we use the same code from the example?

**Comment by brettstack** [comment]
You can use any code you want, but I think it's easiest to start with the sample to have something running, then swap in your Express app.

**Comment by arthurgeron** [comment]
api-gateway does not support gzip encoding, I went trough the same issue and solved it by completely disabling gzip compression on my HTTP response.

**Comment by brettstack** [comment]
Per the example, you can get GZIP working with API Gateway + Binary Support.
