### ISSUE TITLE
waiting for server running 

### ISSUE THREAD

**Issue by shevchenkos** [awslabs/aws-serverless-express#88]
Hi, guys.
I'm trying to use your package.
I faced problem that I received 404 error for first request. 
I was debugging a lot and understood that my express app in aws environment starts long time.
It's the main reason why I get 404 error.
Could you modify 'forwardRequestToNodeServer' method to retry request if there is 404 error?

I found the same problem in this topic https://stackoverflow.com/questions/42190508/aws-api-gateway-cannot-get-when-function-sleeped-for-long-time

**Comment by brettstack** [comment]
I haven't encountered this behavior. Is there anything odd you are doing in your Express layer that might cause this?

**Comment by shevchenkos** [comment]
I measured the time when my express server will reach the 'listening' state.
On my local machine it's less then 2s.
On lambda environment it's 15s. 
All the while I get an error 404.

**Comment by brettstack** [comment]
What's your Lambda memory set to? Try increasing that.

**Comment by shevchenkos** [comment]
A thousand apologies :)
The server initialization code was changed to asynchronous work.
This was done by another team member.
For this reason I was trying to use an un-initialized server.
Once again, I'm sorry that I created issue without understanding my code.

**Comment by brettstack** [comment]
No problem! Glad you got it working.
