### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9005' is therefore not allowed access

### ISSUE THREAD

**Issue by webistan** [awslabs/aws-serverless-express#90]
I am using aws-serverless-express module for using lambda function with express js.

const server = awsServerlessExpress.createServer(app, null, binaryMimeTypes)
exports.handler = function (event, context, callback) {
 awsServerlessExpress.proxy(server, event, context);
}

After that i have create AWS api gateway API with resource and method POST.

when I login , getting error- No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9005' is therefore not allowed access. The response had HTTP status code 403.

**Comment by brettstack** [comment]
Try specifying * in the swagger instead of example.com

**Comment by samikarak** [comment]
where do I excactly find the swagger file ?

**Comment by brettstack** [comment]
This was assuming you were using the example - swagger can be found here https://github.com/awslabs/aws-serverless-express/blob/master/example/simple-proxy-api.yaml. You can either configure OPTIONS at the API Gateway layer, or configure it at the Lambda layer (simpler) by using the cors middleware, see https://github.com/awslabs/aws-serverless-express/blob/master/example/app.js#L4.

**Comment by samikarak** [comment]
I'm actually not using the example, so I got confused a little, the lambda layer would be more appropriate in my case, but I'm using the cors middleware in the app.js and still getting the same error ...

**Comment by brettstack** [comment]
Verify your OPTIONS is going through to Lambda and is returning that
allowed origin.

**Comment by samikarak** [comment]
I can actually catch the OPTIONS request and I'm setting "Access-Control-Allow-Origin" : "*", but the It seems like the next incomming POST request does give me the 502 error.

here is my console log:

> POST https://[awsdomain]/dev/[route]/ 502 ()
> confirm:1 XMLHttpRequest cannot load https://[awsdomain]/dev/[route]/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://[**unkown aws domain**]' is therefore not allowed access. The response had HTTP status code 50

I am actually communication with another lambda express backend on the POST request, but this other backend has not the same domain like the unkown one ... Does lambda itself communicate with any other server under any circumstance ? I hope these are just some missconfigurations of my express app

**Comment by brettstack** [comment]
> Does lambda itself communicate with any other server under any circumstance

No.

> I hope these are just some missconfigurations of my express app

This seems to be the case. It just occurred to me that "No 'Access-Control-Allow-Origin'" error is sometimes a red herring when an error occurred before API Gateway could handle it, and the error response does not include CORS configuration. It sounds like your second lambda express backend has some error.

**Comment by webistan** [comment]
when hit POST request by POSTMAN so working fine but in my angularjs code POST request convert to OPTIONS request in browser so it can't be reach server geetting same error 500 mention above.
how can we solve this issue.

$http({
	url: API,
	method: "POST",
	data:  {"name":"abc"},
	dataType: 'json',
	async: false,
	headers: {"content-type": "application/json"}
}).success(function(data, status) {
    console.log(data);  
})
.error(function (error){
	console.log(error);
});

**Comment by webistan** [comment]
can we create multiple function with proxy  AWS API GATEWAY when using aws-serverless-express in AWS lambda function?

**Comment by brettstack** [comment]
Yes, you just need to configure additional Resources on your API

**Comment by webistan** [comment]
only proxy resource work fine if we create custom resource with method and used than getting error:
missing authentication.
How is it possible for custom resource used in aws-serverless-express in lambda function?

**Comment by webistan** [comment]
solved issue by create resources with new proxy resources.
like this:

/login
 /{proxy}
/dashboard
 /{proxy}

This mechanism solved issue for allowed to different resources communicate different lambda function.

**Comment by raghwendra21** [comment]
Access to XMLHttpRequest at 'https://pwyv0x4l7l.execute-api.us-west-2.amazonaws.com/dev/login' from origin 'http://34.215.214.199:3000' has been blocked by CORS policy: Request header field sessionid is not allowed by Access-Control-Allow-Headers in preflight response.
 login:
    handler: controller/usercontroller.login
    events: 
    - http:
        path: /login
        method: post
        cors:
          origin: 'http://34.215.214.199:3000'
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
            - Access-Control-Allow-Headers
        allowCredentials: false 
function response(statusCode, message) {
    return {
      statusCode: statusCode,
      headers: {
        'Access-Control-Allow-Origin': 'http://34.215.214.199:3000' // Or use wildard * for testing
      },
            body: JSON.stringify(message)
    };
  }

can someone help me now why i am getting this error
