### ISSUE TITLE
"EACCES: permission denied

### ISSUE THREAD

**Issue by ariskemper** [awslabs/aws-serverless-express#96]
I am deploying a simple express application using Claudia and aws-serverless-express: "3.2.0" and on testing I get:

{
  "errorMessage": "EACCES: permission denied, open '/var/task/lambda.js'",
  "errorType": "Error",
  "stackTrace": [
    "Object.fs.openSync (fs.js:641:18)",
    "Object.fs.readFileSync (fs.js:509:33)",
    "Object.Module._extensions..js (module.js:578:20)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)"
  ]
}

**Comment by terencenero007** [comment]
@brettstack Was this issue fixed? If yes, how did you fix this error, as I am facing the same issue?

**Comment by brettstack** [comment]
Sounds like a Claudia or local testing issue.

**Comment by terencenero007** [comment]
I am using serverless framework. The issue is also coming on aws SAM.
